### ISSUE TITLE
QuestLeaveEvent.getQuest()" is null

### ISSUE THREAD

**Issue by aesopcmc** [MagmaGuy/EliteMobs#103]
[21:48:48 ERROR]: Could not pass event QuestLeaveEvent to EliteMobs v7.3.13
java.lang.NullPointerException: Cannot invoke "com.magmaguy.elitemobs.quests.Quest.getQuestName()" because the return value of "com.magmaguy.elitemobs.api.QuestLeaveEvent.getQuest()" is null
        at com.magmaguy.elitemobs.api.QuestLeaveEvent$QuestLeaveEventHandler.onQuestLeave(QuestLeaveEvent.java:39) ~[[娱乐-精英怪物]EliteMobs.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor855.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:git-Paper-272]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:629) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at com.magmaguy.elitemobs.utils.EventCaller.<init>(EventCaller.java:8) ~[[娱乐-精英怪物]EliteMobs.jar:?]
        at com.magmaguy.elitemobs.quests.Quest.stopPlayerQuest(Quest.java:74) ~[[娱乐-精英怪物]EliteMobs.jar:?]
        at com.magmaguy.elitemobs.commands.quests.QuestCommand.leaveQuest(QuestCommand.java:38) ~[[娱乐-精英怪物]EliteMobs.jar:?]
        at com.magmaguy.elitemobs.commands.UserCommands.lambda$new$14(UserCommands.java:198) ~[[娱乐-精英怪物]EliteMobs.jar:?]
        at com.magmaguy.shaded.cloud.execution.CommandExecutionCoordinator$SimpleCoordinator.coordinateExecution(CommandExecutionCoordinator.java:121) ~[[娱乐-精英怪物]EliteMobs.jar:?]
        at com.magmaguy.shaded.cloud.CommandManager.executeCommand(CommandManager.java:176) ~[[娱乐-精英怪物]EliteMobs.jar:?]
        at com.magmaguy.shaded.cloud.bukkit.BukkitCommand.execute(BukkitCommand.java:107) ~[[娱乐-精英怪物]EliteMobs.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.dispatchCommand(CraftServer.java:905) ~[paper-1.18.2.jar:git-Paper-272]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleCommand(ServerGamePacketListenerImpl.java:2306) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2117) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2098) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundChatPacket.handle(ServerboundChatPacket.java:46) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundChatPacket.a(ServerboundChatPacket.java:6) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:51) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.18.2.jar:git-Paper-272]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1399) ~[paper-1.18.2.jar:git-Paper-272]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:188) ~[paper-1.18.2.jar:git-Paper-272]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1376) ~[paper-1.18.2.jar:git-Paper-272]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1369) ~[paper-1.18.2.jar:git-Paper-272]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1347) ~[paper-1.18.2.jar:git-Paper-272]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1229) ~[paper-1.18.2.jar:git-Paper-272]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.18.2.jar:git-Paper-272]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by aesopcmc** [comment]
I m Abandon the quest , the status still Accepted ,, then i click again,  throw error on my server

**Comment by MagmaGuy** [comment]
This should be fixed.
