### ISSUE TITLE
java.lang.IllegalArgumentException: x not finite

### ISSUE THREAD

**Issue by AUndead** [MagmaGuy/EliteMobs#104]
[17:18:15] [Server thread/WARN]: [EliteMobs] Task #562798 for EliteMobs v7.3.14 generated an exception
java.lang.IllegalArgumentException: x not finite
	at org.bukkit.util.NumberConversions.checkFinite(NumberConversions.java:118) ~[purpur-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.util.Vector.checkFinite(Vector.java:814) ~[purpur-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_18_R1.entity.CraftEntity.setVelocity(CraftEntity.java:446) ~[purpur-1.18.1.jar:git-Purpur-1566]
	at com.magmaguy.elitemobs.powers.miscellaneouspowers.Implosion$1.run(Implosion.java:49) ~[EliteMobs-7.3.14.jar:?]
	at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.18.1.jar:git-Purpur-1566]
	at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[purpur-1.18.1.jar:git-Purpur-1566]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1584) ~[purpur-1.18.1.jar:git-Purpur-1566]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:519) ~[purpur-1.18.1.jar:git-Purpur-1566]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1507) ~[purpur-1.18.1.jar:git-Purpur-1566]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1294) ~[purpur-1.18.1.jar:git-Purpur-1566]
	at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:322) ~[purpur-1.18.1.jar:git-Purpur-1566]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]

The server keeps swiping errors in the background, and the server feels a little stuck. The server TPS drops rapidly and then recovers

**Comment by MagmaGuy** [comment]
This should be fixed.
