### ISSUE TITLE
ResultSet closed

### ISSUE THREAD

**Issue by YYYork** [MagmaGuy/EliteMobs#106]
[09:53:21 WARN]: [EliteMobs] Failed to get blob value from database!
[09:53:21 WARN]: [EliteMobs] UUID: a6124caf-bdd2-2b6f-84fd-496763f7356e | Value: QuestStatus
[09:53:21 WARN]: java.sql.SQLException: ResultSet closed
[09:53:21 WARN]:        at org.sqlite.core.CoreResultSet.checkOpen(CoreResultSet.java:76)
[09:53:21 WARN]:        at org.sqlite.jdbc3.JDBC3ResultSet.findColumn(JDBC3ResultSet.java:39)
[09:53:21 WARN]:        at org.sqlite.jdbc3.JDBC3ResultSet.getBytes(JDBC3ResultSet.java:261)
[09:53:21 WARN]:        at EliteMobs (6).jar//com.magmaguy.elitemobs.playerdata.database.PlayerData.getDatabaseBlob(PlayerData.java:348)
[09:53:21 WARN]:        at EliteMobs (6).jar//com.magmaguy.elitemobs.playerdata.database.PlayerData.getQuests(PlayerData.java:239)
[09:53:21 WARN]:        at EliteMobs (6).jar//com.magmaguy.elitemobs.npcs.chatter.NPCProximitySensor.findQuestState(NPCProximitySensor.java:87)
[09:53:21 WARN]:        at EliteMobs (6).jar//com.magmaguy.elitemobs.npcs.chatter.NPCProximitySensor.startQuestIndicator(NPCProximitySensor.java:81)
[09:53:21 WARN]:        at EliteMobs (6).jar//com.magmaguy.elitemobs.npcs.chatter.NPCProximitySensor.access$100(NPCProximitySensor.java:30)
[09:53:21 WARN]:        at EliteMobs (6).jar//com.magmaguy.elitemobs.npcs.chatter.NPCProximitySensor$1.run(NPCProximitySensor.java:62)
[09:53:21 WARN]:        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftTask.run(CraftTask.java:101)
[09:53:21 WARN]:        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483)
[09:53:21 WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1531)
[09:53:21 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:483)
[09:53:21 WARN]:        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1455)
[09:53:21 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1225)
[09:53:21 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315)
[09:53:21 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by MagmaGuy** [comment]
This should be fixed.
