### ISSUE TITLE
About Plugin Error

### ISSUE THREAD

**Issue by HopeLight** [MagmaGuy/EliteMobs#113]
working be in this plugin to appear a error.
 
[17:48:23] [Server thread/ERROR]: Error occurred while enabling EliteMobs v8.0.0-SNAPSHOT-3 (Is it up to date?)
java.lang.NoSuchMethodError: 'com.google.common.collect.Multimap org.bukkit.Material.getDefaultAttributeModifiers(org.bukkit.inventory.EquipmentSlot)'
        at com.magmaguy.elitemobs.api.utils.EliteItemManager.getAttackSpeed(EliteItemManager.java:85) ~[?:?]
        at com.magmaguy.elitemobs.api.utils.EliteItemManager.getWeaponLevel(EliteItemManager.java:130) ~[?:?]
        at com.magmaguy.elitemobs.api.utils.EliteItemManager.isWeapon(EliteItemManager.java:221) ~[?:?]
        at com.magmaguy.elitemobs.api.utils.EliteItemManager.setEliteLevel(EliteItemManager.java:236) ~[?:?]
        at com.magmaguy.elitemobs.items.itemconstructor.ItemConstructor.constructItem(ItemConstructor.java:44) ~[?:?]
        at com.magmaguy.elitemobs.items.customitems.CustomItem.generateDefaultsItemStack(CustomItem.java:375) ~[?:?]
        at com.magmaguy.elitemobs.items.customitems.CustomItem.parseItemTier(CustomItem.java:369) ~[?:?]
        at com.magmaguy.elitemobs.items.customitems.CustomItem.<init>(CustomItem.java:76) ~[?:?]
        at com.magmaguy.elitemobs.items.customitems.CustomItem.initializeCustomItems(CustomItem.java:191) ~[?:?]
        at com.magmaguy.elitemobs.EliteMobs.onEnable(EliteMobs.java:230) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[spigot-1.16.5.jar:3096-Spigot-9fb885e-296df56]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342) ~[spigot-1.16.5.jar:3096-Spigot-9fb885e-296df56]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) ~[spigot-1.16.5.jar:3096-Spigot-9fb885e-296df56]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:492) ~[spigot-1.16.5.jar:3096-Spigot-9fb885e-296df56]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:406) ~[spigot-1.16.5.jar:3096-Spigot-9fb885e-296df56]
        at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:554) ~[spigot-1.16.5.jar:3096-Spigot-9fb885e-296df56]
        at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:257) ~[spigot-1.16.5.jar:3096-Spigot-9fb885e-296df56]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:928) ~[spigot-1.16.5.jar:3096-Spigot-9fb885e-296df56]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$0(MinecraftServer.java:273) ~[spigot-1.16.5.jar:3096-Spigot-9fb885e-29

**Comment by MagmaGuy** [comment]
Try updating, the plugin just updated to snapshot 4.

**Comment by HopeLight** [comment]
> Try updating, the plugin just updated to snapshot 4.

Are sure? My Game version is 1_16_R3 but There a bug my try always.

**Comment by MagmaGuy** [comment]
Latest EliteMobs snapshot doesn't seem to have this error.
