### ISSUE TITLE
model for em_goblin_coins and em_goblin_treasure etc are missing else em_goblin_weapons

### ISSUE THREAD

**Issue by svdermant** [MagmaGuy/EliteMobs#114]
[06:00:36 WARN]: [EliteMobs] Failed to make model entity em_goblin_weapon ! Couldn't assign model or visibility status.
[06:00:36 WARN]: java.lang.NullPointerException: Cannot invoke "com.ticxo.modelengine.api.generator.blueprint.ModelBlueprint.getBones()" because "this.blueprint" is null
[06:00:36 WARN]:        at ModelEngine-2.5.3(2).jar//com.ticxo.modelengine.model.MEActiveModel.generatePartEntities(MEActiveModel.java:123)
[06:00:36 WARN]:        at ModelEngine-2.5.3(2).jar//com.ticxo.modelengine.api.model.AbstractModeledEntity.addActiveModel(AbstractModeledEntity.java:229)
[06:00:36 WARN]:        at ModelEngine-2.5.3(2).jar//com.ticxo.modelengine.model.MEModeledEntity.addActiveModel(MEModeledEntity.java:95)
[06:00:36 WARN]:        at EliteMobs.jar//com.magmaguy.elitemobs.thirdparty.modelengine.CustomModel.<init>(CustomModel.java:69)
[06:00:36 WARN]:        at EliteMobs.jar//com.magmaguy.elitemobs.thirdparty.modelengine.CustomModel.generateCustomModel(CustomModel.java:82)
[06:00:36 WARN]:        at EliteMobs.jar//com.magmaguy.elitemobs.mobconstructor.custombosses.CustomBossMegaConsumer.setCustomModel(CustomBossMegaConsumer.java:129)
[06:00:36 WARN]:        at EliteMobs.jar//com.magmaguy.elitemobs.mobconstructor.custombosses.CustomBossMegaConsumer.applyBossFeatures(CustomBossMegaConsumer.java:86)
[06:00:36 WARN]:        at EliteMobs.jar//com.magmaguy.elitemobs.mobconstructor.custombosses.CustomBossMegaConsumer.lambda$spawn$0(CustomBossMegaConsumer.java:74)
[06:00:36 WARN]:        at org.bukkit.craftbukkit.v1_19_R1.CraftRegionAccessor.addEntity(CraftRegionAccessor.java:533)
[06:00:36 WARN]:        at org.bukkit.craftbukkit.v1_19_R1.CraftRegionAccessor.spawn(CraftRegionAccessor.java:512)
[06:00:36 WARN]:        at org.bukkit.craftbukkit.v1_19_R1.CraftRegionAccessor.spawn(CraftRegionAccessor.java:506)
[06:00:36 WARN]:        at org.bukkit.craftbukkit.v1_19_R1.CraftRegionAccessor.spawn(CraftRegionAccessor.java:497)
[06:00:36 WARN]:        at EliteMobs.jar//com.magmaguy.elitemobs.mobconstructor.custombosses.CustomBossMegaConsumer.spawn(CustomBossMegaConsumer.java:72)
[06:00:36 WARN]:        at EliteMobs.jar//com.magmaguy.elitemobs.mobconstructor.custombosses.CustomBossEntity.spawn(CustomBossEntity.java:203)
[06:00:36 WARN]:        at EliteMobs.jar//com.magmaguy.elitemobs.commands.SpawnCommand.spawnCustomBossCommand(SpawnCommand.java:139)
[06:00:36 WARN]:        at EliteMobs.jar//com.magmaguy.elitemobs.commands.AdminCommands.lambda$new$12(AdminCommands.java:174)
[06:00:36 WARN]:        at EliteMobs.jar//com.magmaguy.shaded.cloud.execution.CommandExecutionHandler.executeFuture(CommandExecutionHandler.java:95)
[06:00:36 WARN]:        at EliteMobs.jar//com.magmaguy.shaded.cloud.execution.CommandExecutionCoordinator$SimpleCoordinator.coordinateExecution(CommandExecutionCoordinator.java:123)
[06:00:36 WARN]:        at EliteMobs.jar//com.magmaguy.shaded.cloud.CommandManager.executeCommand(CommandManager.java:188)
[06:00:36 WARN]:        at EliteMobs.jar//com.magmaguy.shaded.cloud.bukkit.BukkitCommand.execute(BukkitCommand.java:116)[06:00:36 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155)
[06:00:36 WARN]:        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.dispatchCommand(CraftServer.java:911)
[06:00:36 WARN]:        at org.bukkit.craftbukkit.v1_19_R1.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64)
[06:00:36 WARN]:        at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:264)
[06:00:36 WARN]:        at net.minecraft.commands.CommandDispatcher.performCommand(CommandDispatcher.java:305)
[06:00:36 WARN]:        at net.minecraft.commands.CommandDispatcher.a(CommandDispatcher.java:289)
[06:00:36 WARN]:        at net.minecraft.server.network.PlayerConnection.b(PlayerConnection.java:2298)
[06:00:36 WARN]:        at net.minecraft.server.network.PlayerConnection.lambda$handleChatCommand$20(PlayerConnection.java:2252)
[06:00:36 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.b(IAsyncTaskHandler.java:59)
[06:00:36 WARN]:        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)[06:00:36 WARN]:        at net.minecraft.server.TickTask.run(TickTask.java:18)
[06:00:36 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:153)
[06:00:36 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:24)
[06:00:36 WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1360)
[06:00:36 WARN]:        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:185)
[06:00:36 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.x(IAsyncTaskHandler.java:126)
[06:00:36 WARN]:        at net.minecraft.server.MinecraftServer.bh(MinecraftServer.java:1337)
[06:00:36 WARN]:        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1330)
[06:00:36 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:136)
[06:00:36 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1308)
[06:00:36 WARN]:        at net.minecraft.server.MinecraftServer.v(MinecraftServer.java:1196)
[06:00:36 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305)
[06:00:36 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[06:00:36 INFO]: A Weapons Goblin has been sighted!
[06:01:08 INFO]:
[06:01:21 INFO]:

EM Version: 8.0 Snapshot 6
ModelEnginge: R2.5.3-LTS

**Comment by svdermant** [comment]
Also this error occurs:

**Comment by MagmaGuy** [comment]
The latest snapshots just falls back to the normal models, but yeah the reason this happens is because you don't have the models installed.
