### ISSUE TITLE
Error after updating version

### ISSUE THREAD

**Issue by Legendans** [MagmaGuy/EliteMobs#117]
hello author
It doesn't work after I updated from 7.3.18 to 8.0.2
I tried deleting the Multiverse-Core and EliteMobs folders and it worked (but unfortunately lost my previous customizations), but I didn't get this error before 7.3.18

[10:27:30 INFO]: [EliteMobs] Opened database successfully
[10:27:30 INFO]: [PlaceholderAPI] Successfully registered expansion: elitemobs
[10:27:31 WARN]: [EliteMobs] Failed to correctly read entry  in schematic dungeon dark_cathedral_lair.yml
[10:27:31 INFO]: [EliteMobs] Wormhole ag_catacombs_wormhole.yml will not lead anywhere because the dungeon catacombs_lair.yml is not installed!
[10:27:31 INFO]: [EliteMobs] Wormhole ag_pirate_ship_wormhole.yml will not lead anywhere because the dungeon pirate_ship_minidungeon.yml is not installed!
[10:27:31 INFO]: [EliteMobs] Wormhole ag_oasis_wormhole.yml will not lead anywhere because the dungeon oasis_adventure.yml is not installed!
[10:27:31 INFO]: [EliteMobs] Wormhole ag_vampire_manor_wormhole.yml will not lead anywhere because the dungeon vampire_manor.yml is not installed!
[10:27:31 INFO]: [EliteMobs] World your_world_here is not yet loaded! Entities that should spawn there have been queued.
[10:27:31 INFO]: [EliteMobs] Wormhole ag_primis_wormhole.yml will not lead anywhere because the dungeon primis_adventure.yml is not installed!
[10:27:31 INFO]: [EliteMobs] Wormhole ag_colosseum_wormhole.yml will not lead anywhere because the dungeon colosseum_lair.yml is not installed!
[10:27:31 INFO]: [EliteMobs] Wormhole ag_dark_cathedral_wormhole.yml will not lead anywhere because the dungeon dark_cathedral_lair.yml is not installed!
[10:27:31 INFO]: [EliteMobs] Wormhole ag_dark_spire_wormhole.yml will not lead anywhere because the dungeon dark_spire_minidungeon.yml is not installed!
[10:27:31 INFO]: [EliteMobs] Wormhole ag_ruins_wormhole.yml will not lead anywhere because the dungeon the_ruins.yml is not installed!
[10:27:31 INFO]: [EliteMobs] Wormhole ag_airship_wormhole.yml will not lead anywhere because the dungeon airship_minidungeon.yml is not installed!
[10:27:31 ERROR]: Error occurred while enabling EliteMobs v8.0.2 (Is it up to date?)
java.lang.NoClassDefFoundError: org/apache/commons/lang3/tuple/Pair
        at com.magmaguy.elitemobs.dungeons.utility.DungeonUtils.getLowestAndHighestLevels(DungeonUtils.java:32) ~[EliteMobs.jar:?]
        at com.magmaguy.elitemobs.dungeons.WorldDungeonPackage.qualifyEntities(WorldDungeonPackage.java:78) ~[EliteMobs.jar:?]
        at com.magmaguy.elitemobs.dungeons.WorldDungeonPackage.initializeContent(WorldDungeonPackage.java:52) ~[EliteMobs.jar:?]
        at com.magmaguy.elitemobs.EliteMobs.onEnable(EliteMobs.java:265) ~[EliteMobs.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[patched_1.17.1.jar:git-Paper-411]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[patched_1.17.1.jar:git-Paper-411]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[patched_1.17.1.jar:git-Paper-411]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:561) ~[patched_1.17.1.jar:git-Paper-411]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:475) ~[patched_1.17.1.jar:git-Paper-411]
        at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:733) ~[patched_1.17.1.jar:git-Paper-411]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:317) ~[patched_1.17.1.jar:git-Paper-411]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1220) ~[patched_1.17.1.jar:git-Paper-411]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Paper-411]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.ClassNotFoundException: org.apache.commons.lang3.tuple.Pair
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:151) ~[patched_1.17.1.jar:git-Paper-411]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:103) ~[patched_1.17.1.jar:git-Paper-411]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
        ... 14 more
[10:27:31 INFO]: [EliteMobs] Disabling EliteMobs v8.0.2
[10:27:31 INFO]: [EliteMobs] Starting EliteMobs shutdown sequence...
[10:27:31 INFO]: [EliteMobs] Regenerating exploded blocks...
[10:27:31 INFO]: [EliteMobs] Cancelling tasks...
[10:27:31 INFO]: [EliteMobs] Closing wormholes...
[10:27:31 INFO]: [EliteMobs] Spinning Regional Bosses down...
[10:27:31 INFO]: [EliteMobs] Wiping Elite entities clean...
[10:27:31 INFO]: [EliteMobs] Clearing events...
[10:27:31 INFO]: [EliteMobs] Clearing valid worlds...
[10:27:31 INFO]: [EliteMobs] Clearing zone based worlds...
[10:27:31 INFO]: [EliteMobs] Clearing config regional elites...
[10:27:31 INFO]: [EliteMobs] Clearing custom enchantments...
[10:27:31 INFO]: [EliteMobs] Clearing custom items...
[10:27:31 INFO]: [EliteMobs] Clearing Minidungeons...
[10:27:31 INFO]: [EliteMobs] Unregistering placeholders...
[10:27:31 INFO]: [EliteMobs] Unregistering handlers...
[10:27:31 INFO]: [EliteMobs

**Comment by MagmaGuy** [comment]
You need to update the dungeons when updating to 8.0, as is very clearly stated on the changelogs.
