### ISSUE TITLE
After version 8.0.0 Chinese translations are invalid

### ISSUE THREAD

**Issue by dildcc** [MagmaGuy/EliteMobs#121]
After version 8.0.0 Chinese translations are invalid

**Comment by dildcc** [comment]
The version I'm using is 8.3.1

**Comment by dildcc** [comment]
em language chinese_simplified.yml
[08:45:15 WARN]: java.lang.ClassCastException: class com.destroystokyo.paper.console.TerminalConsoleCommandSender cannot be cast to class org.bukkit.entity.Player (com.destroystokyo.paper.console.TerminalConsoleCommandSender and org.bukkit.entity.Player are in unnamed module of loader java.net.URLClassLoader @1963006a)
[08:45:15 WARN]:        at EliteMobs.jar//com.magmaguy.elitemobs.commands.AdminCommands.lambda$new$118(AdminCommands.java:919)
[08:45:15 WARN]:        at EliteMobs.jar//com.magmaguy.shaded.cloud.execution.CommandExecutionHandler.executeFuture(CommandExecutionHandler.java:95)
[08:45:15 WARN]:        at EliteMobs.jar//com.magmaguy.shaded.cloud.execution.CommandExecutionCoordinator$SimpleCoordinator.coordinateExecution(CommandExecutionCoordinator.java:123)
[08:45:15 WARN]:        at EliteMobs.jar//com.magmaguy.shaded.cloud.CommandManager.executeCommand(CommandManager.java:188)
[08:45:15 WARN]:        at EliteMobs.jar//com.magmaguy.shaded.cloud.bukkit.BukkitCommand.execute(BukkitCommand.java:116)
[08:45:15 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:168)
[08:45:15 WARN]:        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.dispatchCommand(CraftServer.java:942)
[08:45:15 WARN]:        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.dispatchServerCommand(CraftServer.java:905)
[08:45:15 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.bg(DedicatedServer.java:512)
[08:45:15 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:486)
[08:45:15 WARN]:        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1443)
[08:45:15 WARN]:        at net.minecraft.server.MinecraftServer.v(MinecraftServer.java:1213)
[08:45:15 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:310)
[08:45:15 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[08:45:15 INFO]: [Example] An internal error occurred while attempting to perform this command.
