### ISSUE TITLE
Blacksmith's Wont Open Shops

### ISSUE THREAD

**Issue by TheGamingNoodle** [MagmaGuy/EliteMobs#14]
On The EliteMobs_adventurers_guild_world Sometimes, The BlackSmiths Will Not Open Their Shop When Right Clicking. I went to the NPCs.yml and set Disappears at night: to false and it will still do this. 

I first I thought it was because of the spawn region I made but even removing it won't solve the problem. I have to restart the server for it to register it again. Also the NPC's used take damage it would be nice if one could modify this so players won't be able to kill them.

**Comment by TheGamingNoodle** [comment]
After Investigating more I discovered that the guild attendant also has the same issue; when I try to bypass the NPC by using the command I get an internal error.
`[22:25:07] [Server thread/INFO]: TheGamingNoodle issued server command: /em gettier
[22:25:07] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'em' in plugin EliteMobs v7.0.3
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:48) ~[spigot-1.13.2.jar:git-Spigot-f09662d-7c395d4]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot-1.13.2.jar:git-Spigot-f09662d-7c395d4]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:704) ~[spigot-1.13.2.jar:git-Spigot-f09662d-7c395d4]
	at net.minecraft.server.v1_13_R2.PlayerConnection.handleCommand(PlayerConnection.java:1620) ~[spigot-1.13.2.jar:git-Spigot-f09662d-7c395d4]
	at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1460) ~[spigot-1.13.2.jar:git-Spigot-f09662d-7c395d4]
	at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[spigot-1.13.2.jar:git-Spigot-f09662d-7c395d4]
	at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[spigot-1.13.2.jar:git-Spigot-f09662d-7c395d4]
	at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:9) ~[spigot-1.13.2.jar:git-Spigot-f09662d-7c395d4]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_181]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_181]
	at net.minecraft.server.v1_13_R2.SystemUtils.a(SourceFile:199) [spigot-1.13.2.jar:git-Spigot-f09662d-7c395d4]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:896) [spigot-1.13.2.jar:git-Spigot-f09662d-7c395d4]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [spigot-1.13.2.jar:git-Spigot-f09662d-7c395d4]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:831) [spigot-1.13.2.jar:git-Spigot-f09662d-7c395d4]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:729) [spigot-1.13.2.jar:git-Spigot-f09662d-7c395d4]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
Caused by: java.lang.ArrayIndexOutOfBoundsException: 1
	at com.magmaguy.elitemobs.commands.CommandHandler.onCommand(CommandHandler.java:200) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot-1.13.2.jar:git-Spigot-f09662d-7c395d4]
	... 15 more`

**Comment by MagmaGuy** [comment]
These issues have been resolved months ago in the 1.14 branch, download the dev version if you want a fully functioning version.
