### ISSUE TITLE
Could not pass event CreatureSpawnEvent

### ISSUE THREAD

**Issue by mitchngwen** [MagmaGuy/EliteMobs#146]
`[21:07:57] [Server thread/ERROR]: Could not pass event CreatureSpawnEvent to EliteMobs v8.7.6
java.lang.IllegalArgumentException: Health value (35.0) must be between 0 and 24.5. (attribute base value: 35.0)
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:482) ~[guava-32.1.2-jre.jar:?]
	at org.bukkit.craftbukkit.v1_20_R3.entity.CraftLivingEntity.setHealth(CraftLivingEntity.java:107) ~[purpur-1.20.4.jar:git-Purpur-2162]
	at com.magmaguy.elitemobs.mobconstructor.EliteEntity.setMaxHealth(EliteEntity.java:321) ~[EliteMobs8.7.7.jar:?]
	at com.magmaguy.elitemobs.mobconstructor.EliteEntity.setLivingEntity(EliteEntity.java:297) ~[EliteMobs8.7.7.jar:?]
	at com.magmaguy.elitemobs.mobconstructor.EliteEntity.<init>(EliteEntity.java:155) ~[EliteMobs8.7.7.jar:?]
	at com.magmaguy.elitemobs.mobspawning.NaturalMobSpawnEventHandler.onSpawn(NaturalMobSpawnEventHandler.java:173) ~[EliteMobs8.7.7.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor680.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:git-Purpur-2162]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[purpur-1.20.4.jar:git-Purpur-2162]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[purpur-1.20.4.jar:git-Purpur-2162]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:617) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R3.event.CraftEventFactory.callCreatureSpawnEvent(CraftEventFactory.java:798) ~[purpur-1.20.4.jar:git-Purpur-2162]
	at org.bukkit.craftbukkit.v1_20_R3.event.CraftEventFactory.doEntityAddEventCalling(CraftEventFactory.java:702) ~[purpur-1.20.4.jar:git-Purpur-2162]
	at net.minecraft.server.level.ServerLevel.addEntity(ServerLevel.java:1782) ~[?:?]
	at net.minecraft.server.level.ServerLevel.addFreshEntity(ServerLevel.java:1704) ~[?:?]
	at net.minecraft.world.level.ServerLevelAccessor.lambda$addFreshEntityWithPassengers$0(ServerLevelAccessor.java:16) ~[?:?]
	at java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:411) ~[?:?]
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762) ~[?:?]
	at net.minecraft.world.level.ServerLevelAccessor.addFreshEntityWithPassengers(ServerLevelAccessor.java:16) ~[?:?]
	at net.minecraft.world.level.NaturalSpawner.spawnCategoryForPosition(NaturalSpawner.java:301) ~[?:?]
	at net.minecraft.world.level.NaturalSpawner.spawnCategoryForChunk(NaturalSpawner.java:212) ~[?:?]
	at net.minecraft.world.level.NaturalSpawner.spawnForChunk(NaturalSpawner.java:182) ~[?:?]
	at net.minecraft.server.level.ServerChunkCache.tickChunks(ServerChunkCache.java:645) ~[?:?]
	at net.minecraft.server.level.ServerChunkCache.tick(ServerChunkCache.java:491) ~[?:?]
	at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:889) ~[?:?]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1759) ~[purpur-1.20.4.jar:git-Purpur-2162]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:487) ~[purpur-1.20.4.jar:git-Purpur-2162]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1558) ~[purpur-1.20.4.jar:git-Purpur-2162]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1246) ~[purpur-1.20.4.jar:git-Purpur-2162]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[purpur-1.20.4.jar:git-Purpur-2162]
	at java.lang.Thread.run(Thread.java:840) ~[?:?]`

AND

`[20:59:21] [Server thread/ERROR]: Could not pass event CreatureSpawnEvent to EliteMobs v8.7.6
java.lang.IllegalArgumentException: Health value (35.0) must be between 0 and 26.809999465942383. (attribute base value: 35.0)
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:482) ~[guava-32.1.2-jre.jar:?]
	at org.bukkit.craftbukkit.v1_20_R3.entity.CraftLivingEntity.setHealth(CraftLivingEntity.java:107) ~[purpur-1.20.4.jar:git-Purpur-2162]
	at com.magmaguy.elitemobs.mobconstructor.EliteEntity.setMaxHealth(EliteEntity.java:321) ~[EliteMobs8.7.7.jar:?]
	at com.magmaguy.elitemobs.mobconstructor.EliteEntity.setLivingEntity(EliteEntity.java:297) ~[EliteMobs8.7.7.jar:?]
	at com.magmaguy.elitemobs.mobconstructor.EliteEntity.<init>(EliteEntity.java:155) ~[EliteMobs8.7.7.jar:?]
	at com.magmaguy.elitemobs.mobspawning.NaturalMobSpawnEventHandler.onSpawn(NaturalMobSpawnEventHandler.java:173) ~[EliteMobs8.7.7.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor680.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:git-Purpur-2162]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[purpur-1.20.4.jar:git-Purpur-2162]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[purpur-1.20.4.jar:git-Purpur-2162]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:617) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R3.event.CraftEventFactory.callCreatureSpawnEvent(CraftEventFactory.java:798) ~[purpur-1.20.4.jar:git-Purpur-2162]
	at org.bukkit.craftbukkit.v1_20_R3.event.CraftEventFactory.doEntityAddEventCalling(CraftEventFactory.java:702) ~[purpur-1.20.4.jar:git-Purpur-2162]
	at net.minecraft.server.level.ServerLevel.addEntity(ServerLevel.java:1782) ~[?:?]
	at net.minecraft.server.level.ServerLevel.addFreshEntity(ServerLevel.java:1704) ~[?:?]
	at net.minecraft.world.level.ServerLevelAccessor.lambda$addFreshEntityWithPassengers$0(ServerLevelAccessor.java:16) ~[?:?]
	at java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:411) ~[?:?]
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762) ~[?:?]
	at net.minecraft.world.level.ServerLevelAccessor.addFreshEntityWithPassengers(ServerLevelAccessor.java:16) ~[?:?]
	at net.minecraft.world.level.NaturalSpawner.spawnCategoryForPosition(NaturalSpawner.java:301) ~[?:?]
	at net.minecraft.world.level.NaturalSpawner.spawnCategoryForChunk(NaturalSpawner.java:212) ~[?:?]
	at net.minecraft.world.level.NaturalSpawner.spawnForChunk(NaturalSpawner.java:182) ~[?:?]
	at net.minecraft.server.level.ServerChunkCache.tickChunks(ServerChunkCache.java:645) ~[?:?]
	at net.minecraft.server.level.ServerChunkCache.tick(ServerChunkCache.java:491) ~[?:?]
	at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:889) ~[?:?]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1759) ~[purpur-1.20.4.jar:git-Purpur-2162]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:487) ~[purpur-1.20.4.jar:git-Purpur-2162]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1558) ~[purpur-1.20.4.jar:git-Purpur-2162]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1246) ~[purpur-1.20.4.jar:git-Purpur-2162]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[purpur-1.20.4.jar:git-Purpur-2162]
	at java.lang.Thread.run(Thread.java:840) ~[?:?]`

**Comment by mitchngwen** [comment]
There are tones more and I do apologize for not using pastebin.

**Comment by mitchngwen** [comment]
Also I would like to say thank you for making this plugin! It is very cool!

**Comment by MagmaGuy** [comment]
This is because you are running another plugin which is modifying mob health. Elitemobs can't do anything about that. Either find a way for the other plugin not to do that, get rid of the other plugin or ask the other plugin's author to stop modifying the health of named mobs.
