### ISSUE TITLE
an error occured while enabling the plugin

### ISSUE THREAD

**Issue by rakahago** [MagmaGuy/EliteMobs#155]
java.lang.VerifyError: Bad return type
Exception Details:
  Location:
    javassist/f.b(Ljava/lang/String;Z)Ljavassist/CtClass; @67: areturn
  Reason:
    Type 'javassist/l' (current frame, stack[0]) is not assignable to 'javassist/CtClass' (from method signature)
  Current Frame:
    bci: @67
    flags: { }
    locals: { 'javassist/f', 'java/lang/String' }
    stack: { 'javassist/l' }
  Bytecode:
    0000000: 2b03 b600 9510 5ba0 0008 2bb8 00a1 4c2b
    0000010: 12a3 b600 a799 002f 2b03 2b10 5bb6 00ab
    0000020: b600 af4e 1c99 000b 2a2d b600 87c7 000d
    0000030: 2a2d b600 b2c7 0005 01b0 bb00 b459 2b2a
    0000040: b700 b7b0 2a2b b600 b2c7 0005 01b0 bb00
    0000050: 8059 2b2a b700 b8b0                    
  Stackmap Table:
    same_frame(@15)
    full_frame(@48,{Object[#2],Object[#126],Top,Object[#126]},{})
    chop_frame(@58,2)
    same_frame(@68)
    same_frame(@78)
        at com.magmaguy.elitemobs.EliteMobsL10.a(Unknown Source) ~[EliteMobs (1).jar:?]
        at com.magmaguy.elitemobs.EliteMobs.onEnable(EliteMobs.java) ~[EliteMobs (1).jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:656) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:567) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:640) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:439) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:345) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1116) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:322) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[03:05:48 INFO]: [EliteMobs] Disabling EliteMobs v8.7.15

Server Version : 1.20.1 
Software : PurpurMC

**Comment by MagmaGuy** [comment]
You most likely have a virus.
