### ISSUE TITLE
Getting "missing required data class org.bukkit.Color" spammed in server log.

### ISSUE THREAD

**Issue by Holt31** [MagmaGuy/EliteMobs#157]
While playing normaly, the following exception is spammed into my console.
It does not seem to cause any problems with gameplay, but I'm not sure, because the server is lagging a bit, when this exception is appearing.

```[21:31:47] [Server thread/WARN]: [EliteMobs] Task #78594 for EliteMobs v8.7.16 generated an exception
java.lang.IllegalArgumentException: missing required data class org.bukkit.Color
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:218) ~[guava-32.1.2-jre.jar:?]
	at org.bukkit.craftbukkit.CraftParticle.createParticleParam(CraftParticle.java:68) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
	at org.bukkit.craftbukkit.CraftWorld.spawnParticle(CraftWorld.java:2262) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
	at org.bukkit.craftbukkit.CraftWorld.spawnParticle(CraftWorld.java:2250) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
	at org.bukkit.craftbukkit.CraftWorld.spawnParticle(CraftWorld.java:2239) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
	at org.bukkit.craftbukkit.CraftWorld.spawnParticle(CraftWorld.java:2229) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
	at org.bukkit.craftbukkit.CraftWorld.spawnParticle(CraftWorld.java:2224) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
	at EliteMobs-LATEST-[8.7.16].jar/com.magmaguy.elitemobs.mobconstructor.custombosses.CustomBossTrail$1.run(CustomBossTrail.java:64) ~[EliteMobs-LATEST-[8.7.16].jar:?]
	at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
	at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:482) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1699) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:467) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1571) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1231) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
```

I'm using:
```
This server is running Paper version 1.20.6-147-ver/1.20.6@e41d44f (2024-06-17T19:24:35Z) (Implementing API version 1.20.6-R0.1-SNAPSHOT)
```

More info:
The server runs inside a custom-made docker image on a kubernetes cluster with autoplug support.
That does not affect anything, but could be "good to know".

**Comment by Cozary** [comment]
The same thing has happened to me. I think it happens when an event appears, but I'm not sure.


```
[EliteMobs] Task #3844778 for EliteMobs v8.7.16 generated an exception
java.lang.IllegalArgumentException: missing required data class org.bukkit.Color
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:218) ~[guava-32.1.2-jre.jar:?]
        at org.bukkit.craftbukkit.CraftParticle.createParticleParam(CraftParticle.java:68) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
        at org.bukkit.craftbukkit.CraftWorld.spawnParticle(CraftWorld.java:2262) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
        at org.bukkit.craftbukkit.CraftWorld.spawnParticle(CraftWorld.java:2250) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
        at org.bukkit.craftbukkit.CraftWorld.spawnParticle(CraftWorld.java:2239) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
        at org.bukkit.craftbukkit.CraftWorld.spawnParticle(CraftWorld.java:2229) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
        at org.bukkit.craftbukkit.CraftWorld.spawnParticle(CraftWorld.java:2224) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
        at EliteMobs.jar/com.magmaguy.elitemobs.mobconstructor.custombosses.CustomBossTrail$1.run(CustomBossTrail.java:64) ~[EliteMobs.jar:?]
        at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
        at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:482) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1699) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:467) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1571) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1231) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
```

**Comment by ZacharyElkins** [comment]
Same.

1.20.6 paper / purpur server

**Comment by MagmaGuy** [comment]
To be clear:

# For Minecraft 1.19.4-1.20.4 use the last version of EliteMobs 8

# For Minecraft 1.21+ use EliteMobs 9

# Minecraft 1.20.5 and 1.20.6 are not supported, as they have all the API changes but none of the features!
