### ISSUE TITLE
Getting "class org.bukkit.inventory.InventoryView, but interface was expected" spammed in server log.

### ISSUE THREAD

**Issue by Holt31** [MagmaGuy/EliteMobs#158]
While playing normaly, the following exception is spammed into my console.
It does not seem to cause any problems with gameplay, but I'm not sure, because the server is lagging a bit, when this exception is appearing.
```
[16:20:56 ERROR]: Could not pass event InventoryCloseEvent to EliteMobs v9.0.0
java.lang.IncompatibleClassChangeError: Found class org.bukkit.inventory.InventoryView, but interface was expected
        at EliteMobs-LATEST-[9.0.0].jar/com.magmaguy.elitemobs.npcs.chatter.NPCProximitySensor.onInventoryClose(NPCProximitySensor.java:172) ~[EliteMobs-LATEST-[9.0.0].jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor524.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:1.20.6-147-e41d44f]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.event.CraftEventFactory.handleInventoryCloseEvent(CraftEventFactory.java:1621) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClose(ServerGamePacketListenerImpl.java:2929) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClose(ServerGamePacketListenerImpl.java:2922) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
        at net.minecraft.network.protocol.game.ServerboundContainerClosePacket.handle(ServerboundContainerClosePacket.java:33) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
        at net.minecraft.network.protocol.game.ServerboundContainerClosePacket.handle(ServerboundContainerClosePacket.java:15) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:55) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1511) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:195) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1488) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1411) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1377) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1238) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
```
I'm using:
```
This server is running Paper version 1.20.6-147-ver/1.20.6@e41d44f (2024-06-17T19:24:35Z) (Implementing API version 1.20.6-R0.1-SNAPSHOT)
```
More info:
The server runs inside a custom-made docker image on a kubernetes cluster with autoplug support.
That does not affect anything, but could be "good to know".

**Comment by Holt31** [comment]
I did the mistake that I was using EliteMobs v9.0.0 on 1.20.6-147. 9.0.0 only works on 1.21 or above.
After downgrading, I did not get this error anymore.
I would suggest to put the info that version 9.0.0 is not supported in 1.20.6 not only under the updates tab of spigot, but as well as on the main page, otherwise it will be overlooked. The main page only states that the build below is supported from 1.19.4 to 1.20.4, but not 1.20.6.
![image](https://github.com/MagmaGuy/EliteMobs/assets/44321142/1198e3b0-e906-4790-906d-889b98f4252f)
![image](https://github.com/MagmaGuy/EliteMobs/assets/44321142/1f177d6f-b183-4565-b032-38c1faefc225)
