### ISSUE TITLE
Eror can't Enable Plugin Elite mobs and better structure

### ISSUE THREAD

**Issue by Naufal90** [MagmaGuy/EliteMobs#164]
++++++++++++++++++++(ELITE MOBS)++++++++++++++++++++++
[15:22:44] [Server thread/INFO]: [EliteMobs] Enabling EliteMobs v8.7.16
[15:22:44] [Server thread/ERROR]: Error occurred while enabling EliteMobs v8.7.16 (Is it up to date?)
java.lang.VerifyError: Bad return type
Exception Details:
  Location:
    javassist/f.b(Ljava/lang/String;Z)Ljavassist/CtClass; @67: areturn
  Reason:
    Type 'javassist/l' (current frame, stack[0]) is not assignable to 'javassist/CtClass' (from method signature)
  Current Frame:
    bci: @67
    flags: { }
    locals: { 'javassist/f', 'java/lang/String' }
    stack: { 'javassist/l' }
  Bytecode:
    0000000: 2b03 b600 9510 5ba0 0008 2bb8 00a1 4c2b
    0000010: 12a3 b600 a799 002f 2b03 2b10 5bb6 00ab
    0000020: b600 af4e 1c99 000b 2a2d b600 87c7 000d
    0000030: 2a2d b600 b2c7 0005 01b0 bb00 b459 2b2a
    0000040: b700 b7b0 2a2b b600 b2c7 0005 01b0 bb00
    0000050: 8059 2b2a b700 b8b0                    
  Stackmap Table:
    same_frame(@15)
    full_frame(@48,{Object[#2],Object[#126],Top,Object[#126]},{})
    chop_frame(@58,2)
    same_frame(@68)
    same_frame(@78)

	at com.magmaguy.elitemobs.EliteMobsL10.a(Unknown Source) ~[EliteMobs (1).jar:?]
	at com.magmaguy.elitemobs.EliteMobs.onEnable(EliteMobs.java) ~[EliteMobs (1).jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189) ~[paper-1.20.1.jar:git-Paper-196]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.20.1.jar:git-Paper-196]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:642) ~[paper-1.20.1.jar:git-Paper-196]
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:553) ~[paper-1.20.1.jar:git-Paper-196]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:635) ~[paper-1.20.1.jar:git-Paper-196]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:434) ~[paper-1.20.1.jar:git-Paper-196]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:308) ~[paper-1.20.1.jar:git-Paper-196]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1100) ~[paper-1.20.1.jar:git-Paper-196]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.20.1.jar:git-Paper-196]
	at java.lang.Thread.run(Thread.java:1583) ~[?:?]
[15:22:44] [Server thread/INFO]: [EliteMobs] Disabling EliteMobs v8.7.16
[15:22:44] [Server thread/INFO]: [EliteMobs] Starting EliteMobs shutdown sequence...
[15:22:44] [Server thread/INFO]: [EliteMobs] Regenerating exploded blocks...
[15:22:44] [Server thread/INFO]: [EliteMobs] Cancelling tasks...
[15:22:44] [Server thread/INFO]: [EliteMobs] Closing wormholes...
[15:22:44] [Server thread/INFO]: [EliteMobs] Spinning Regional Bosses down...
[15:22:44] [Server thread/INFO]: [EliteMobs] Wiping Elite entities clean...
[15:22:44] [Server thread/INFO]: [EliteMobs] Clearing events...
[15:22:44] [Server thread/INFO]: [EliteMobs] Clearing valid worlds...
[15:22:44] [Server thread/INFO]: [EliteMobs] Clearing zone based worlds...
[15:22:44] [Server thread/INFO]: [EliteMobs] Clearing config regional elites...
[15:22:44] [Server thread/INFO]: [EliteMobs] Clearing custom enchantments...
[15:22:44] [Server thread/INFO]: [EliteMobs] Clearing custom items...
[15:22:44] [Server thread/INFO]: [EliteMobs] Clearing Minidungeons...
[15:22:44] [Server thread/INFO]: [EliteMobs] Unregistering placeholders...
[15:22:44] [Server thread/INFO]: [EliteMobs] Unregistering handlers...
[15:22:44] [Server thread/INFO]: [EliteMobs] Clearing Treasure Chests...
[15:22:44] [Server thread/INFO]: [EliteMobs] Untracking quests...
[15:22:44] [Server thread/INFO]: [EliteMobs] Saving EliteMobs databases...
[15:22:44] [Server thread/INFO]: [EliteMobs] All done! Good night.

++++++++++++++++(BETTER STRUCTURE)+++++++++++++++++++
[15:22:49] [Server thread/INFO]: [BetterStructures] Enabling BetterStructures v1.6.11
[15:22:49] [Server thread/ERROR]: Error occurred while enabling BetterStructures v1.6.11 (Is it up to date?)
java.lang.LinkageError: loader constraint violation: when resolving method 'javassist.d javassist.f.a(javassist.d)' the class loader 'BetterStructures.jar' @700ff8c4 of the current class, com/magmaguy/betterstructures/BetterStructuresL10, and the class loader 'ViaVersion-5.0.2.jar' @1594c98 for the method's defining class, javassist/f, have different Class objects for the type javassist/d used in the signature (com.magmaguy.betterstructures.BetterStructuresL10 is in unnamed module of loader 'BetterStructures.jar' @700ff8c4, parent loader java.net.URLClassLoader @41cf53f9; javassist.f is in unnamed module of loader 'ViaVersion-5.0.2.jar' @1594c98, parent loader java.net.URLClassLoader @41cf53f9)
	at com.magmaguy.betterstructures.BetterStructuresL10.a(Unknown Source) ~[BetterStructures.jar:?]
	at com.magmaguy.betterstructures.BetterStructures.onEnable(BetterStructures.java) ~[BetterStructures.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189) ~[paper-1.20.1.jar:git-Paper-196]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.20.1.jar:git-Paper-196]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:642) ~[paper-1.20.1.jar:git-Paper-196]
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:553) ~[paper-1.20.1.jar:git-Paper-196]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:635) ~[paper-1.20.1.jar:git-Paper-196]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:434) ~[paper-1.20.1.jar:git-Paper-196]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:308) ~[paper-1.20.1.jar:git-Paper-196]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1100) ~[paper-1.20.1.jar:git-Paper-196]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.20.1.jar:git-Paper-196]
	at java.lang.Thread.run(Thread.java:1583) ~[?:?]
[15:22:49] [Server thread/INFO]: [BetterStructures] Disabling BetterStructures v1.6.11
[15:22:49] [Server thread/ERROR]: Error occurred (in the plugin loader) while disabling BetterStructures v1.6.11 (Is it up to date?)
java.lang.IllegalArgumentException: Cannot cancel tasks of null plugin
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:145) ~[guava-31.1-jre.jar:?]
	at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftScheduler.cancelTasks(CraftScheduler.java:319) ~[paper-1.20.1.jar:git-Paper-196]
	at com.magmaguy.betterstructures.BetterStructures.onDisable(BetterStructures.java:74) ~[BetterStructures.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:283) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.disablePlugin(PaperPluginInstanceManager.java:224) ~[paper-1.20.1.jar:git-Paper-196]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.disablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.20.1.jar:git-Paper-196]
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:537) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:193) ~[paper-1.20.1.jar:git-Paper-196]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.20.1.jar:git-Paper-196]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:642) ~[paper-1.20.1.jar:git-Paper-196]
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:553) ~[paper-1.20.1.jar:git-Paper-196]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:635) ~[paper-1.20.1.jar:git-Paper-196]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:434) ~[paper-1.20.1.jar:git-Paper-196]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:308) ~[paper-1.20.1.jar:git-Paper-196]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1100) ~[paper-1.20.1.jar:git-Paper-196]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.20.1.jar:git-Paper-196]
	at java.lang.Thread.run(Thread.java:1583) ~[?:?]

**Comment by MagmaGuy** [comment]
You have a virus called hostflo.w
