### ISSUE TITLE
Failed to update database value

### ISSUE THREAD

**Issue by servicomcr** [MagmaGuy/EliteMobs#165]
[19:54:13 WARN]: [EliteMobs] Failed to update database value.
[19:54:13 WARN]: com.mysql.cj.jdbc.exceptions.CommunicationsException: Communications link failure
[19:54:13 WARN]: 
[19:54:13 WARN]: The last packet successfully received from the server was 3,730,454 milliseconds ago. The last packet sent successfully to the server was 3,730,455 milliseconds ago.
[19:54:13 WARN]:        at com.mysql.cj.jdbc.exceptions.SQLError.createCommunicationsException(SQLError.java:165)
[19:54:13 WARN]:        at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:55)
[19:54:13 WARN]:        at com.mysql.cj.jdbc.StatementImpl.executeUpdateInternal(StatementImpl.java:1454)
[19:54:13 WARN]:        at com.mysql.cj.jdbc.StatementImpl.executeLargeUpdate(StatementImpl.java:2185)
[19:54:13 WARN]:        at com.mysql.cj.jdbc.StatementImpl.executeUpdate(StatementImpl.java:1331)
[19:54:13 WARN]:        at EliteMobs.jar//com.magmaguy.elitemobs.playerdata.database.PlayerData$2.run(PlayerData.java:346)
[19:54:13 WARN]:        at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:86)
[19:54:13 WARN]:        at org.bukkit.craftbukkit.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[19:54:13 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[19:54:13 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[19:54:13 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[19:54:13 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)
[19:54:13 WARN]: Caused by: com.mysql.cj.exceptions.CJCommunicationsException: Communications link failure
[19:54:13 WARN]: 
[19:54:13 WARN]: The last packet successfully received from the server was 3,730,454 milliseconds ago. The last packet sent successfully to the server was 3,730,455 milliseconds ago.
[19:54:13 WARN]:        at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
[19:54:13 WARN]:        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
[19:54:13 WARN]:        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
[19:54:13 WARN]:        at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:52)
[19:54:13 WARN]:        at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:95)
[19:54:13 WARN]:        at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:140)
[19:54:13 WARN]:        at com.mysql.cj.exceptions.ExceptionFactory.createCommunicationsException(ExceptionFactory.java:156)
[19:54:13 WARN]:        at com.mysql.cj.protocol.a.NativeProtocol.readMessage(NativeProtocol.java:597)
[19:54:13 WARN]:        at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:775)
[19:54:13 WARN]:        at com.mysql.cj.protocol.a.NativeProtocol.sendCommand(NativeProtocol.java:714)
[19:54:13 WARN]:        at com.mysql.cj.protocol.a.NativeProtocol.sendQueryPacket(NativeProtocol.java:946)
[19:54:13 WARN]:        at com.mysql.cj.NativeSession.execSQL(NativeSession.java:803)
[19:54:13 WARN]:        at com.mysql.cj.jdbc.StatementImpl.executeUpdateInternal(StatementImpl.java:1417)
[19:54:13 WARN]:        ... 9 more
[19:54:13 WARN]: Caused by: java.net.SocketException: Connection timed out
[19:54:13 WARN]:        at java.base/sun.nio.ch.SocketDispatcher.read0(Native Method)
[19:54:13 WARN]:        at java.base/sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:47)
[19:54:13 WARN]:        at java.base/sun.nio.ch.NioSocketImpl.tryRead(NioSocketImpl.java:256)
[19:54:13 WARN]:        at java.base/sun.nio.ch.NioSocketImpl.implRead(NioSocketImpl.java:310)
[19:54:13 WARN]:        at java.base/sun.nio.ch.NioSocketImpl.read(NioSocketImpl.java:346)
[19:54:13 WARN]:        at java.base/sun.nio.ch.NioSocketImpl$1.read(NioSocketImpl.java:796)
[19:54:13 WARN]:        at java.base/java.net.Socket$SocketInputStream.read(Socket.java:1099)
[19:54:13 WARN]:        at com.mysql.cj.protocol.ReadAheadInputStream.fill(ReadAheadInputStream.java:98)
[19:54:13 WARN]:        at com.mysql.cj.protocol.ReadAheadInputStream.readFromUnderlyingStreamIfNecessary(ReadAheadInputStream.java:141)
[19:54:13 WARN]:        at com.mysql.cj.protocol.ReadAheadInputStream.read(ReadAheadInputStream.java:171)
[19:54:13 WARN]:        at java.base/java.io.FilterInputStream.read(FilterInputStream.java:119)
[19:54:13 WARN]:        at com.mysql.cj.protocol.a.SimplePacketReader.readHeader(SimplePacketReader.java:54)
[19:54:13 WARN]:        at com.mysql.cj.protocol.a.SimplePacketReader.readHeader(SimplePacketReader.java:36)
[19:54:13 WARN]:        at com.mysql.cj.protocol.a.TimeTrackingPacketReader.readHeader(TimeTrackingPacketReader.java:43)
[19:54:13 WARN]:        at com.mysql.cj.protocol.a.TimeTrackingPacketReader.readHeader(TimeTrackingPacketReader.java:32)
[19:54:13 WARN]:        at com.mysql.cj.protocol.a.MultiPacketReader.readHeader(MultiPacketReader.java:45)
[19:54:13 WARN]:        at com.mysql.cj.protocol.a.MultiPacketReader.readHeader(MultiPacketReader.java:35)
[19:54:13 WARN]:        at com.mysql.cj.protocol.a.NativeProtocol.readMessage(NativeProtocol.java:591)
[19:54:13 WARN]:        ... 14 more

**Comment by MagmaGuy** [comment]
Closing based on the log sent in discord seems to be a problem with your database
