### ISSUE TITLE
Could not pass event PlayerDeathEvent to EliteMobs v9.1.4

### ISSUE THREAD

**Issue by servicomcr** [MagmaGuy/EliteMobs#171]
java.lang.NullPointerException: null
        at java.base/java.util.Objects.requireNonNull(Objects.java:233) ~[?:?]
        at java.base/java.util.ImmutableCollections.listFromArray(ImmutableCollections.java:192) ~[?:?]
        at java.base/java.util.List.of(List.java:1172) ~[?:?]
        at EliteMobs.jar/com.magmaguy.elitemobs.collateralminecraftchanges.AlternativeDurabilityLoss.doDurabilityLoss(AlternativeDurabilityLoss.java:44) ~[EliteMobs.jar:?]
        at EliteMobs.jar/com.magmaguy.elitemobs.collateralminecraftchanges.AlternativeDurabilityLoss.onPlayerDeath(AlternativeDurabilityLoss.java:78) ~[EliteMobs.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor523.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:1.21-2272-b2d1fea]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[purpur-1.21.jar:1.21-2272-b2d1fea]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[purpur-1.21.jar:1.21-2272-b2d1fea]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.event.CraftEventFactory.callPlayerDeathEvent(CraftEventFactory.java:1033) ~[purpur-1.21.jar:1.21-2272-b2d1fea]
        at net.minecraft.server.level.ServerPlayer.die(ServerPlayer.java:1057) ~[purpur-1.21.jar:1.21-2272-b2d1fea]
        at net.minecraft.world.entity.LivingEntity.hurt(LivingEntity.java:1639) ~[purpur-1.21.jar:1.21-2272-b2d1fea]
        at net.minecraft.world.entity.player.Player.hurt(Player.java:1041) ~[purpur-1.21.jar:1.21-2272-b2d1fea]
        at net.minecraft.server.level.ServerPlayer.hurt(ServerPlayer.java:1235) ~[purpur-1.21.jar:1.21-2272-b2d1fea]
        at net.minecraft.world.entity.projectile.FireworkRocketEntity.dealExplosionDamage(FireworkRocketEntity.java:244) ~[purpur-1.21.jar:1.21-2272-b2d1fea]
        at net.minecraft.world.entity.projectile.FireworkRocketEntity.explode(FireworkRocketEntity.java:198) ~[purpur-1.21.jar:1.21-2272-b2d1fea]
        at net.minecraft.world.entity.projectile.FireworkRocketEntity.onHitBlock(FireworkRocketEntity.java:222) ~[purpur-1.21.jar:1.21-2272-b2d1fea]
        at net.minecraft.world.entity.projectile.Projectile.onHit(Projectile.java:267) ~[purpur-1.21.jar:1.21-2272-b2d1fea]
        at net.minecraft.world.entity.projectile.Projectile.hitTargetOrDeflectSelf(Projectile.java:233) ~[purpur-1.21.jar:1.21-2272-b2d1fea]
        at net.minecraft.world.entity.projectile.Projectile.preHitTargetOrDeflectSelf(Projectile.java:212) ~[purpur-1.21.jar:1.21-2272-b2d1fea]
        at net.minecraft.world.entity.projectile.FireworkRocketEntity.tick(FireworkRocketEntity.java:171) ~[purpur-1.21.jar:1.21-2272-b2d1fea]
        at net.minecraft.server.level.ServerLevel.tickNonPassenger(ServerLevel.java:1359) ~[purpur-1.21.jar:1.21-2272-b2d1fea]
        at net.minecraft.world.level.Level.guardEntityTick(Level.java:1466) ~[purpur-1.21.jar:1.21-2272-b2d1fea]
        at net.minecraft.server.level.ServerLevel.lambda$tick$6(ServerLevel.java:801) ~[purpur-1.21.jar:1.21-2272-b2d1fea]
        at net.minecraft.world.level.entity.EntityTickList.forEach(EntityTickList.java:39) ~[purpur-1.21.jar:1.21-2272-b2d1fea]
        at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:781) ~[purpur-1.21.jar:1.21-2272-b2d1fea]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1842) ~[purpur-1.21.jar:1.21-2272-b2d1fea]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:509) ~[purpur-1.21.jar:1.21-2272-b2d1fea]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1633) ~[purpur-1.21.jar:1.21-2272-b2d1fea]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1333) ~[purpur-1.21.jar:1.21-2272-b2d1fea]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:333) ~[purpur-1.21.jar:1.21-2272-b2d1fea]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]

**Comment by MagmaGuy** [comment]
This has since been fixed.
