### ISSUE TITLE
Failed to update database value.

### ISSUE THREAD

**Issue by servicomcr** [MagmaGuy/EliteMobs#175]
When I try to connect to DB it gives this error.

[21:26:56 WARN]: [EliteMobs] Failed to update database value.
[21:26:56 WARN]: com.mysql.cj.jdbc.exceptions.CommunicationsException: Communications link failure
[21:26:56 WARN]: 
[21:26:56 WARN]: The last packet successfully received from the server was 3,399,570 milliseconds ago. The last packet sent successfully to the server was 3,399,572 milliseconds ago.
[21:26:56 WARN]:        at com.mysql.cj.jdbc.exceptions.SQLError.createCommunicationsException(SQLError.java:165)
[21:26:56 WARN]:        at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:55)
[21:26:56 WARN]:        at com.mysql.cj.jdbc.StatementImpl.executeUpdateInternal(StatementImpl.java:1454)
[21:26:56 WARN]:        at com.mysql.cj.jdbc.StatementImpl.executeLargeUpdate(StatementImpl.java:2185)
[21:26:56 WARN]:        at com.mysql.cj.jdbc.StatementImpl.executeUpdate(StatementImpl.java:1331)
[21:26:56 WARN]:        at EliteMobs.jar//com.magmaguy.elitemobs.playerdata.database.PlayerData$2.run(PlayerData.java:346)
[21:26:56 WARN]:        at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:86)
[21:26:56 WARN]:        at org.bukkit.craftbukkit.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[21:26:56 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[21:26:56 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[21:26:56 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[21:26:56 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)
[21:26:56 WARN]: Caused by: com.mysql.cj.exceptions.CJCommunicationsException: Communications link failure
[21:26:56 WARN]: 
[21:26:56 WARN]: The last packet successfully received from the server was 3,399,570 milliseconds ago. The last packet sent successfully to the server was 3,399,572 milliseconds ago.
[21:26:56 WARN]:        at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
[21:26:56 WARN]:        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
[21:26:56 WARN]:        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
[21:26:56 WARN]:        at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:52)
[21:26:56 WARN]:        at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:95)
[21:26:56 WARN]:        at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:140)
[21:26:56 WARN]:        at com.mysql.cj.exceptions.ExceptionFactory.createCommunicationsException(ExceptionFactory.java:156)
[21:26:56 WARN]:        at com.mysql.cj.protocol.a.NativeProtocol.readMessage(NativeProtocol.java:597)
[21:26:56 WARN]:        at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:775)
[21:26:56 WARN]:        at com.mysql.cj.protocol.a.NativeProtocol.sendCommand(NativeProtocol.java:714)
[21:26:56 WARN]:        at com.mysql.cj.protocol.a.NativeProtocol.sendQueryPacket(NativeProtocol.java:946)
[21:26:56 WARN]:        at com.mysql.cj.NativeSession.execSQL(NativeSession.java:803)
[21:26:56 WARN]:        at com.mysql.cj.jdbc.StatementImpl.executeUpdateInternal(StatementImpl.java:1417)
[21:26:56 WARN]:        ... 9 more
[21:26:56 WARN]: Caused by: java.net.SocketException: Connection timed out
[21:26:56 WARN]:        at java.base/sun.nio.ch.SocketDispatcher.read0(Native Method)
[21:26:56 WARN]:        at java.base/sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:47)
[21:26:56 WARN]:        at java.base/sun.nio.ch.NioSocketImpl.tryRead(NioSocketImpl.java:256)
[21:26:56 WARN]:        at java.base/sun.nio.ch.NioSocketImpl.implRead(NioSocketImpl.java:310)
[21:26:56 WARN]:        at java.base/sun.nio.ch.NioSocketImpl.read(NioSocketImpl.java:346)
[21:26:56 WARN]:        at java.base/sun.nio.ch.NioSocketImpl$1.read(NioSocketImpl.java:796)
[21:26:56 WARN]:        at java.base/java.net.Socket$SocketInputStream.read(Socket.java:1099)
[21:26:56 WARN]:        at com.mysql.cj.protocol.ReadAheadInputStream.fill(ReadAheadInputStream.java:98)
[21:26:56 WARN]:        at com.mysql.cj.protocol.ReadAheadInputStream.readFromUnderlyingStreamIfNecessary(ReadAheadInputStream.java:141)
[21:26:56 WARN]:        at com.mysql.cj.protocol.ReadAheadInputStream.read(ReadAheadInputStream.java:171)
[21:26:56 WARN]:        at java.base/java.io.FilterInputStream.read(FilterInputStream.java:119)
[21:26:56 WARN]:        at com.mysql.cj.protocol.FullReadInputStream.readFully(FullReadInputStream.java:55)
[21:26:56 WARN]:        at com.mysql.cj.protocol.a.SimplePacketReader.readHeaderLocal(SimplePacketReader.java:72)
[21:26:56 WARN]:        at com.mysql.cj.protocol.a.SimplePacketReader.readHeader(SimplePacketReader.java:54)
[21:26:56 WARN]:        at com.mysql.cj.protocol.a.SimplePacketReader.readHeader(SimplePacketReader.java:36)
[21:26:56 WARN]:        at com.mysql.cj.protocol.a.TimeTrackingPacketReader.readHeader(TimeTrackingPacketReader.java:43)
[21:26:56 WARN]:        at com.mysql.cj.protocol.a.TimeTrackingPacketReader.readHeader(TimeTrackingPacketReader.java:32)
[21:26:56 WARN]:        at com.mysql.cj.protocol.a.MultiPacketReader.readHeader(MultiPacketReader.java:45)
[21:26:56 WARN]:        at com.mysql.cj.protocol.a.MultiPacketReader.readHeader(MultiPacketReader.java:35)
[21:26:56 WARN]:        at com.mysql.cj.protocol.a.NativeProtocol.readMessage(NativeProtocol.java:591)
[21:26:56 WARN]:        ... 14 more

**Comment by Euphillya** [comment]
Check your database

**Comment by servicomcr** [comment]
It's blank  It is not generated by elitemobs

**Comment by MagmaGuy** [comment]
## Semi-automated AI reply
Replying on behalf of MagmaGuy based on his instructions.

Closing this legacy ticket because it predates the current EliteMobs 10.x release series and concerns a much older generation of the plugin.

Please update to the current release, 10.8.1. If this issue or request still applies, please open a new ticket with the current plugin/server versions and up-to-date details.
