### ISSUE TITLE
 EliteMobs tried and failed to spawn wood_league_wave_3_melee.yml . Possible reasons for this:

### ISSUE THREAD

**Issue by servicomcr** [MagmaGuy/EliteMobs#177]
[10:08:26 WARN]: [EliteMobs] EliteMobs tried and failed to spawn wood_league_wave_3_melee.yml . Possible reasons for this:
[10:08:26 WARN]: [EliteMobs] - The region was protected by a plugin (most likely)
[10:08:26 WARN]: [EliteMobs] - The spawn was interfered with by some incompatible third party plugin
[10:08:26 WARN]: [EliteMobs] Debug data: 
[10:08:26 WARN]: [EliteMobs] Chunk is loaded: true
[10:08:26 WARN]: [EliteMobs] Attempted spawn location: Location{world=CraftWorld{name=em_adventurers_guild},x=219.5,y=71.0,z=316.5,pitch=0.0,yaw=0.0}
[10:08:26 WARN]: java.lang.Exception: Stack trace
[10:08:26 WARN]:        at java.base/java.lang.Thread.dumpStack(Thread.java:2209)
[10:08:26 WARN]:        at EliteMobs.jar//com.magmaguy.magmacore.util.Logger.warn(Logger.java:30)
[10:08:26 WARN]:        at EliteMobs.jar//com.magmaguy.elitemobs.mobconstructor.custombosses.CustomBossEntity.spawn(CustomBossEntity.java:250)
[10:08:26 WARN]:        at EliteMobs.jar//com.magmaguy.elitemobs.mobconstructor.custombosses.CustomBossEntity.spawn(CustomBossEntity.java:192)
[10:08:26 WARN]:        at EliteMobs.jar//com.magmaguy.elitemobs.instanced.arena.ArenaInstance.spawnBosses(ArenaInstance.java:257)
[10:08:26 WARN]:        at EliteMobs.jar//com.magmaguy.elitemobs.instanced.arena.ArenaInstance.lambda$nextWave$4(ArenaInstance.java:213)
[10:08:26 WARN]:        at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:86)
[10:08:26 WARN]:        at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:475)
[10:08:26 WARN]:        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1761)
[10:08:26 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:509)
[10:08:26 WARN]:        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1633)
[10:08:26 WARN]:        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1333)
[10:08:26 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:333)
[10:08:26 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)
[10:08:26 WARN]: [EliteMobs] Arena Wood League failed to spawn boss wood_league_wave_3_melee.yml

**Comment by MagmaGuy** [comment]
## Semi-automated AI reply
Replying on behalf of MagmaGuy based on his instructions.

Closing this legacy ticket because it predates the current EliteMobs 10.x release series and concerns a much older generation of the plugin.

Please update to the current release, 10.8.1. If this issue or request still applies, please open a new ticket with the current plugin/server versions and up-to-date details.
