### ISSUE TITLE
[EliteMobs] Failed to update database value.

### ISSUE THREAD

**Issue by servicomcr** [MagmaGuy/EliteMobs#180]
It always doesn't matter if the server is newly built it gives this problem, I have tried the elite many times and it gives that same error

[22:25:43] [Craft Scheduler Thread - 128 - EliteMobs/WARN]: [EliteMobs] Failed to update database value.
[22:25:43] [Craft Scheduler Thread - 124 - EliteMobs/WARN]: [EliteMobs] Failed to update database value.
[22:25:43] [Craft Scheduler Thread - 128 - EliteMobs/WARN]: java.sql.SQLException: No operations allowed after statement closed.
[22:25:43] [Craft Scheduler Thread - 128 - EliteMobs/WARN]: 	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:121)
[22:25:43] [Craft Scheduler Thread - 128 - EliteMobs/WARN]: 	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:89)
[22:25:43] [Craft Scheduler Thread - 128 - EliteMobs/WARN]: 	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:81)
[22:25:43] [Craft Scheduler Thread - 128 - EliteMobs/WARN]: 	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:55)
[22:25:43] [Craft Scheduler Thread - 128 - EliteMobs/WARN]: 	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:65)
[22:25:43] [Craft Scheduler Thread - 128 - EliteMobs/WARN]: 	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:73)
[22:25:43] [Craft Scheduler Thread - 115 - EliteMobs/WARN]: [EliteMobs] Failed to update database value.
[22:25:43] [Craft Scheduler Thread - 128 - EliteMobs/WARN]: 	at com.mysql.cj.jdbc.StatementImpl.getResultSetConcurrency(StatementImpl.java:1795)
[22:25:43] [Craft Scheduler Thread - 128 - EliteMobs/WARN]: 	at com.mysql.cj.jdbc.result.ResultSetFactory.<init>(ResultSetFactory.java:52)
[22:25:43] [Craft Scheduler Thread - 128 - EliteMobs/WARN]: 	at com.mysql.cj.jdbc.StatementImpl.<init>(StatementImpl.java:256)
[22:25:43] [Craft Scheduler Thread - 128 - EliteMobs/WARN]: 	at com.mysql.cj.jdbc.ConnectionImpl.createStatement(ConnectionImpl.java:1099)
[22:25:43] [Craft Scheduler Thread - 128 - EliteMobs/WARN]: 	at com.mysql.cj.jdbc.ConnectionImpl.createStatement(ConnectionImpl.java:1094)
[22:25:43] [Craft Scheduler Thread - 128 - EliteMobs/WARN]: 	at EliteMobs.jar//com.magmaguy.elitemobs.playerdata.database.PlayerData$2.run(PlayerData.java:337)
[22:25:43] [Craft Scheduler Thread - 128 - EliteMobs/WARN]: 	at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:86)
[22:25:43] [Craft Scheduler Thread - 128 - EliteMobs/WARN]: 	at org.bukkit.craftbukkit.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[22:25:43] [Craft Scheduler Thread - 128 - EliteMobs/WARN]: 	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[22:25:43] [Craft Scheduler Thread - 128 - EliteMobs/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[22:25:43] [Craft Scheduler Thread - 128 - EliteMobs/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[22:25:43] [Craft Scheduler Thread - 128 - EliteMobs/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:1583)
[22:25:43] [Craft Scheduler Thread - 128 - EliteMobs/WARN]: Caused by: com.mysql.cj.exceptions.StatementIsClosedException: No operations allowed after statement closed.
[22:25:43] [Craft Scheduler Thread - 128 - EliteMobs/WARN]: 	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
[22:25:43] [Craft Scheduler Thread - 128 - EliteMobs/WARN]: 	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
[22:25:43] [Craft Scheduler Thread - 128 - EliteMobs/WARN]: 	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
[22:25:43] [Craft Scheduler Thread - 128 - EliteMobs/WARN]: 	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:52)
[22:25:43] [Craft Scheduler Thread - 128 - EliteMobs/WARN]: 	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:76)
[22:25:43] [Craft Scheduler Thread - 128 - EliteMobs/WARN]: 	at com.mysql.cj.jdbc.StatementImpl.checkClosed(StatementImpl.java:352)
[22:25:43] [Craft Scheduler Thread - 128 - EliteMobs/WARN]: 	at com.mysql.cj.jdbc.StatementImpl.getResultSetConcurrency(StatementImpl.java:1793)

https://pastebin.com/jxaaYdjn

**Comment by MagmaGuy** [comment]
## Semi-automated AI reply
Replying on behalf of MagmaGuy based on his instructions.

Closing this legacy ticket because it predates the current EliteMobs 10.x release series and concerns a much older generation of the plugin.

Please update to the current release, 10.8.1. If this issue or request still applies, please open a new ticket with the current plugin/server versions and up-to-date details.
