### ISSUE TITLE
[EliteMobs] Task #581869 for EliteMobs v9.1.11 generated an exception

### ISSUE THREAD

**Issue by servicomcr** [MagmaGuy/EliteMobs#182]
[23:43:53 WARN]: [EliteMobs] Task #581869 for EliteMobs v9.1.11 generated an exception
java.lang.IllegalArgumentException: LAVA isn't an item
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:143) ~[guava-32.1.2-jre.jar:?]
        at org.bukkit.inventory.ItemStack.of(ItemStack.java:69) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:149) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:128) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:115) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:98) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
        at EliteMobs.jar/com.magmaguy.elitemobs.magmacore.util.ItemStackGenerator.generateItemStack(ItemStackGenerator.java:174) ~[EliteMobs.jar:?]
        at EliteMobs.jar/com.magmaguy.elitemobs.magmacore.util.ItemStackGenerator.generateItemStack(ItemStackGenerator.java:165) ~[EliteMobs.jar:?]
        at EliteMobs.jar/com.magmaguy.elitemobs.magmacore.util.ItemStackGenerator.generateItemStack(ItemStackGenerator.java:157) ~[EliteMobs.jar:?]
        at EliteMobs.jar/com.magmaguy.elitemobs.mobconstructor.custombosses.CustomBossTrail$2.run(CustomBossTrail.java:87) ~[EliteMobs.jar:?]
        at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:86) ~[purpur-1.21.jar:1.21-2284-4e55e26]
        at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:475) ~[purpur-1.21.jar:1.21-2284-4e55e26]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1762) ~[purpur-1.21.jar:1.21-2284-4e55e26]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:509) ~[purpur-1.21.jar:1.21-2284-4e55e26]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1634) ~[purpur-1.21.jar:1.21-2284-4e55e26]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1334) ~[purpur-1.21.jar:1.21-2284-4e55e26]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:333) ~[purpur-1.21.jar:1.21-2284-4e55e26]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]

**Comment by MagmaGuy** [comment]
## Semi-automated AI reply
Replying on behalf of MagmaGuy based on his instructions.

Closing this legacy ticket because it predates the current EliteMobs 10.x release series and concerns a much older generation of the plugin.

Please update to the current release, 10.8.1. If this issue or request still applies, please open a new ticket with the current plugin/server versions and up-to-date details.
