### ISSUE TITLE
java.lang.NoClassDefFoundError: com/magmaguy/freeminecraftmodels/utils/VersionChecker

### ISSUE THREAD

**Issue by handy-git** [MagmaGuy/EliteMobs#184]
`
[16:15:31 ERROR]: Error occurred while enabling EliteMobs v9.2.0 (Is it up to date?)
java.lang.NoClassDefFoundError: com/magmaguy/freeminecraftmodels/utils/VersionChecker
        at EliteMobs-9.2.0.jar/com.magmaguy.elitemobs.magmacore.util.ItemStackGenerator.generateItemStack(ItemStackGenerator.java:162) ~[EliteMobs-9.2.0.jar:?]
        at EliteMobs-9.2.0.jar/com.magmaguy.elitemobs.config.menus.premade.ItemEnchantmentMenuConfig.processAdditionalFields(ItemEnchantmentMenuConfig.java:94) ~[EliteMobs-9.2.0.jar:?]
        at EliteMobs-9.2.0.jar/com.magmaguy.elitemobs.config.menus.MenusConfigFields.processConfigFields(MenusConfigFields.java:14) ~[EliteMobs-9.2.0.jar:?]
        at EliteMobs-9.2.0.jar/com.magmaguy.elitemobs.magmacore.config.CustomConfig.initialize(CustomConfig.java:159) ~[EliteMobs-9.2.0.jar:?]
        at EliteMobs-9.2.0.jar/com.magmaguy.elitemobs.magmacore.config.CustomConfig.fileInitializer(CustomConfig.java:108) ~[EliteMobs-9.2.0.jar:?]
        at EliteMobs-9.2.0.jar/com.magmaguy.elitemobs.magmacore.config.CustomConfig.directoryCrawler(CustomConfig.java:94) ~[EliteMobs-9.2.0.jar:?]
        at EliteMobs-9.2.0.jar/com.magmaguy.elitemobs.magmacore.config.CustomConfig.<init>(CustomConfig.java:78) ~[EliteMobs-9.2.0.jar:?]
        at EliteMobs-9.2.0.jar/com.magmaguy.elitemobs.config.menus.MenusConfig.<init>(MenusConfig.java:12) ~[EliteMobs-9.2.0.jar:?]
        at EliteMobs-9.2.0.jar/com.magmaguy.elitemobs.EliteMobs.initializeConfigs(EliteMobs.java:100) ~[EliteMobs-9.2.0.jar:?]
        at EliteMobs-9.2.0.jar/com.magmaguy.elitemobs.EliteMobs.onEnable(EliteMobs.java:162) ~[EliteMobs-9.2.0.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288) ~[paper-api-1.21.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[paper-1.21.4.jar:1.21.4-14-b746d9d]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.21.4.jar:1.21.4-14-b746d9d]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[paper-api-1.21.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:655) ~[paper-1.21.4.jar:1.21.4-14-b746d9d]
        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:604) ~[paper-1.21.4.jar:1.21.4-14-b746d9d]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:769) ~[paper-1.21.4.jar:1.21.4-14-b746d9d]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:531) ~[paper-1.21.4.jar:1.21.4-14-b746d9d]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:326) ~[paper-1.21.4.jar:1.21.4-14-b746d9d]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1236) ~[paper-1.21.4.jar:1.21.4-14-b746d9d]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:341) ~[paper-1.21.4.jar:1.21.4-14-b746d9d]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.ClassNotFoundException: com.magmaguy.freeminecraftmodels.utils.VersionChecker
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:197) ~[paper-api-1.21.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:164) ~[paper-api-1.21.4-R0.1-SNAPSHOT.jar:?]
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
        ... 22 more

`

**Comment by SeeEmAge95** [comment]
Same error here

[15:32:53] [Server thread/INFO]: [EliteMobs] Enabling EliteMobs v9.2.0
[15:32:53] [Server thread/INFO]:  _____ _     _____ _____ ________  ______________  _____
[15:32:53] [Server thread/INFO]: |  ___| |   |_   _|_   _|  ___|  \/  |  _  | ___ \/  ___|
[15:32:53] [Server thread/INFO]: | |__ | |     | |   | | | |__ | .  . | | | | |_/ /\ `--.
[15:32:53] [Server thread/INFO]: |  __|| |     | |   | | |  __|| |\/| | | | | ___ \ `--. \
[15:32:53] [Server thread/INFO]: | |___| |_____| |_  | | | |___| |  | \ \_/ / |_/ //\__/ /
[15:32:53] [Server thread/INFO]: \____/\_____/\___/  \_/ \____/\_|  |_/\___/\____/ \____/
[15:32:53] [Server thread/INFO]: By MagmaGuy - v. 9.2.0
[15:32:53] [Server thread/INFO]: [EliteMobs] Supported server version detected: v1_21_R3
[15:32:53] [Server thread/INFO]: [org.reflections.Reflections] Reflections took 38 ms to scan 1 urls, producing 1 keys and 14 values
[15:32:53] [Server thread/INFO]: [org.reflections.Reflections] Reflections took 6 ms to scan 1 urls, producing 1 keys and 59 values
[15:32:53] [Server thread/INFO]: [org.reflections.Reflections] Reflections took 7 ms to scan 1 urls, producing 1 keys and 15 values
[15:32:54] [Server thread/INFO]: Environment: Environment[sessionHost=https://sessionserver.mojang.com, servicesHost=https://api.minecraftservices.com, name=PROD]
[15:32:54] [Server thread/ERROR]: Error occurred while enabling EliteMobs v9.2.0 (Is it up to date?)
java.lang.NoClassDefFoundError: com/magmaguy/freeminecraftmodels/utils/VersionChecker
at EliteMobs.jar/com.magmaguy.elitemobs.magmacore.util.ItemStackGenerator.generateItemStack(ItemStackGenerator.java:162) ~[EliteMobs.jar:?]
at EliteMobs.jar/com.magmaguy.elitemobs.config.menus.premade.ItemEnchantmentMenuConfig.processAdditionalFields(ItemEnchantmentMenuConfig.java:94) ~[EliteMobs.jar:?]
at EliteMobs.jar/com.magmaguy.elitemobs.config.menus.MenusConfigFields.processConfigFields(MenusConfigFields.java:14) ~[EliteMobs.jar:?]
at EliteMobs.jar/com.magmaguy.elitemobs.magmacore.config.CustomConfig.initialize(CustomConfig.java:159) ~[EliteMobs.jar:?]
at EliteMobs.jar/com.magmaguy.elitemobs.magmacore.config.CustomConfig.fileInitializer(CustomConfig.java:108) ~[EliteMobs.jar:?]
at EliteMobs.jar/com.magmaguy.elitemobs.magmacore.config.CustomConfig.directoryCrawler(CustomConfig.java:94) ~[EliteMobs.jar:?]
at EliteMobs.jar/com.magmaguy.elitemobs.magmacore.config.CustomConfig.<init>(CustomConfig.java:78) ~[EliteMobs.jar:?]
at EliteMobs.jar/com.magmaguy.elitemobs.config.menus.MenusConfig.<init>(MenusConfig.java:12) ~[EliteMobs.jar:?]
at EliteMobs.jar/com.magmaguy.elitemobs.EliteMobs.initializeConfigs(EliteMobs.java:100) ~[EliteMobs.jar:?]
at EliteMobs.jar/com.magmaguy.elitemobs.EliteMobs.onEnable(EliteMobs.java:162) ~[EliteMobs.jar:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288) ~[paper-api-1.21.4-R0.1-SNAPSHOT.jar:?]
at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[paper-1.21.4.jar:1.21.4-15-bb76819]
at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.21.4.jar:1.21.4-15-bb76819]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[paper-api-1.21.4-R0.1-SNAPSHOT.jar:?]
at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:655) ~[paper-1.21.4.jar:1.21.4-15-bb76819]
at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:604) ~[paper-1.21.4.jar:1.21.4-15-bb76819]
at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:769) ~[paper-1.21.4.jar:1.21.4-15-bb76819]
at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:531) ~[paper-1.21.4.jar:1.21.4-15-bb76819]
at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:326) ~[paper-1.21.4.jar:1.21.4-15-bb76819]
at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1236) ~[paper-1.21.4.jar:1.21.4-15-bb76819]
at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:341) ~[paper-1.21.4.jar:1.21.4-15-bb76819]
at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.ClassNotFoundException: com.magmaguy.freeminecraftmodels.utils.VersionChecker
at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:197) ~[paper-api-1.21.4-R0.1-SNAPSHOT.jar:?]
at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:164) ~[paper-api-1.21.4-R0.1-SNAPSHOT.jar:?]
at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
... 22 more
[15:32:54] [Server thread/INFO]: [EliteMobs] Disabling EliteMobs v9.2.0
[15:32:54] [Server thread/INFO]: [EliteMobs] Starting EliteMobs shutdown sequence...
[15:32:54] [Server thread/INFO]: [EliteMobs] Saving EliteMobs databases...
[15:32:54] [Server thread/INFO]: [EliteMobs] All done! Good night.

**Comment by SeeEmAge95** [comment]
Found a fix!
You have to install this plugin. It is working very well for me now.

https://www.spigotmc.org/resources/free-minecraft-models.111660/

**Comment by Holt31** [comment]
@SeeEmAge95 thanks for the fix.

Tbh. I don't think that this is intended as it is now.
Elitemobs never needed external plugins to work properly.
