### ISSUE TITLE
Task #43576 for EliteMobs v9.2.0 generated an exception

### ISSUE THREAD

**Issue by servicomcr** [MagmaGuy/EliteMobs#185]
[19:21:50 WARN]: [EliteMobs] Task #43576 for EliteMobs v9.2.0 generated an exception
java.lang.NoSuchMethodError: 'void org.bukkit.inventory.meta.ItemMeta.setItemModel(org.bukkit.NamespacedKey)'
        at EliteMobs.jar/com.magmaguy.elitemobs.items.ItemLootShower.setCoinModel(ItemLootShower.java:346) ~[EliteMobs.jar:?]
        at EliteMobs.jar/com.magmaguy.elitemobs.items.ItemLootShower.generateCurrencyItem(ItemLootShower.java:216) ~[EliteMobs.jar:?]
        at EliteMobs.jar/com.magmaguy.elitemobs.items.ItemLootShower.dropOne(ItemLootShower.java:238) ~[EliteMobs.jar:?]
        at EliteMobs.jar/com.magmaguy.elitemobs.items.ItemLootShower$3.run(ItemLootShower.java:184) ~[EliteMobs.jar:?]
        at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:86) ~[paper-1.21.1.jar:1.21.1-131-84281ce]
        at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:475) ~[paper-1.21.1.jar:1.21.1-131-84281ce]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1724) ~[paper-1.21.1.jar:1.21.1-131-84281ce]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:473) ~[paper-1.21.1.jar:1.21.1-131-84281ce]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1596) ~[paper-1.21.1.jar:1.21.1-131-84281ce]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1302) ~[paper-1.21.1.jar:1.21.1-131-84281ce]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:329) ~[paper-1.21.1.jar:1.21.1-131-84281ce]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]

**Comment by MagmaGuy** [comment]
## Semi-automated AI reply
Replying on behalf of MagmaGuy based on his instructions.

Closing this legacy ticket because it predates the current EliteMobs 10.x release series and concerns a much older generation of the plugin.

Please update to the current release, 10.8.1. If this issue or request still applies, please open a new ticket with the current plugin/server versions and up-to-date details.
