### ISSUE TITLE
HELP ME

### ISSUE THREAD

**Issue by LFMJUN** [MagmaGuy/EliteMobs#23]
I have an error while using EM.
Can you help me?
`[18:37:46] [Server thread/INFO]: Little_Fish_Man issued server command: /em quest
[18:37:50] [Server thread/ERROR]: Could not pass event InventoryClickEvent to EliteMobs v7.1.0
java.lang.ArrayIndexOutOfBoundsException: -1
	at java.util.ArrayList.elementData(ArrayList.java:422) ~[?:1.8.0_222]
	at java.util.ArrayList.get(ArrayList.java:435) ~[?:1.8.0_222]
	at com.magmaguy.elitemobs.quests.QuestsMenu.onTierQuestClick(QuestsMenu.java:101) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor387.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[akarin-1.13.2-520.jar:git-Akarin-"9c4d9da"]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[akarin-1.13.2-520.jar:git-Akarin-"9c4d9da"]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:66) ~[akarin-1.13.2-520.jar:git-Akarin-"9c4d9da"]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:540) ~[akarin-1.13.2-520.jar:git-Akarin-"9c4d9da"]
	at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:2369) ~[akarin-1.13.2-520.jar:git-Akarin-"9c4d9da"]
	at net.minecraft.server.v1_13_R2.PacketPlayInWindowClick.a(SourceFile:33) ~[akarin-1.13.2-520.jar:git-Akarin-"9c4d9da"]
	at net.minecraft.server.v1_13_R2.PacketPlayInWindowClick.a(SourceFile:10) ~[akarin-1.13.2-520.jar:git-Akarin-"9c4d9da"]
	at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:15) ~[akarin-1.13.2-520.jar:git-Akarin-"9c4d9da"]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_222]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_222]
	at net.minecraft.server.v1_13_R2.SystemUtils.a(SystemUtils.java:108) ~[akarin-1.13.2-520.jar:git-Akarin-"9c4d9da"]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1031) ~[akarin-1.13.2-520.jar:git-Akarin-"9c4d9da"]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:440) ~[akarin-1.13.2-520.jar:git-Akarin-"9c4d9da"]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:953) ~[akarin-1.13.2-520.jar:git-Akarin-"9c4d9da"]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:850) ~[akarin-1.13.2-520.jar:git-Akarin-"9c4d9da"]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]
`

**Comment by MagmaGuy** [comment]
It's a bug in the current version, I'll fix it as soon as I have some time.

**Comment by LFMJUN** [comment]
Ok thanks
