### ISSUE TITLE
Issues

### ISSUE THREAD

**Issue by LFMJUN** [MagmaGuy/EliteMobs#24]
Hello.
When i using the zombieking's axe it warns this.
`[15:36:24] [Server thread/WARN]: java.lang.IllegalArgumentException: Material must be a block!
[15:36:24] [Server thread/WARN]: 	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:122)
[15:36:24] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.block.CraftBlockState.setType(CraftBlockState.java:126)
[15:36:24] [Server thread/WARN]: 	at net.coreprotect.consumer.Queue.queueContainerBreak(Queue.java:118)
[15:36:24] [Server thread/WARN]: 	at net.coreprotect.database.Database.containerBreakCheck(Database.java:70)
[15:36:24] [Server thread/WARN]: 	at net.coreprotect.listener.EntityListener.onEntityDamageByEntity(EntityListener.java:246)
[15:36:24] [Server thread/WARN]: 	at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37)
[15:36:24] [Server thread/WARN]: 	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
[15:36:24] [Server thread/WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:66)
[15:36:24] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:540)
[15:36:24] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.event.CraftEventFactory.callEvent(CraftEventFactory.java:104)
[15:36:24] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:834)
[15:36:24] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:733)
[15:36:24] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.event.CraftEventFactory.handleNonLivingEntityDamageEvent(CraftEventFactory.java:885)
[15:36:24] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.event.CraftEventFactory.handleNonLivingEntityDamageEvent(CraftEventFactory.java:871)
[15:36:24] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.EntityArmorStand.damageEntity(EntityArmorStand.java:425)
[15:36:24] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.entity.CraftLivingEntity.damage(CraftLivingEntity.java:274)
[15:36:24] [Server thread/WARN]: 	at com.magmaguy.elitemobs.events.BossSpecialAttackDamage.dealSpecialDamage(BossSpecialAttackDamage.java:23)
[15:36:24] [Server thread/WARN]: 	at com.magmaguy.elitemobs.items.customenchantments.FlamethrowerEnchantment.doDamage(FlamethrowerEnchantment.java:50)
[15:36:24] [Server thread/WARN]: 	at com.magmaguy.elitemobs.items.customenchantments.FlamethrowerEnchantment.access$400(FlamethrowerEnchantment.java:25)
[15:36:24] [Server thread/WARN]: 	at com.magmaguy.elitemobs.items.customenchantments.FlamethrowerEnchantment$FlamethrowerEnchantmentEvents$2.run(FlamethrowerEnchantment.java:133)
[15:36:24] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:84)
[15:36:24] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:449)
[15:36:24] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1023)
[15:36:24] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:440)
[15:36:24] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:953)
[15:36:24] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:850)
[15:36:24] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[15:36:24] [Server thread/WARN]: java.lang.IllegalArgumentException: Material must be a block!
[15:36:24] [Server thread/WARN]: 	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:122)
[15:36:24] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.block.CraftBlockState.setType(CraftBlockState.java:126)
[15:36:24] [Server thread/WARN]: 	at net.coreprotect.consumer.Queue.queueContainerBreak(Queue.java:118)
[15:36:24] [Server thread/WARN]: 	at net.coreprotect.database.Database.containerBreakCheck(Database.java:70)
[15:36:24] [Server thread/WARN]: 	at net.coreprotect.listener.EntityListener.onEntityDamageByEntity(EntityListener.java:246)
[15:36:24] [Server thread/WARN]: 	at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37)
[15:36:24] [Server thread/WARN]: 	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
[15:36:24] [Server thread/WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:66)
[15:36:24] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:540)
[15:36:24] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.event.CraftEventFactory.callEvent(CraftEventFactory.java:104)
[15:36:24] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:834)
[15:36:24] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:733)
[15:36:24] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.event.CraftEventFactory.handleNonLivingEntityDamageEvent(CraftEventFactory.java:885)
[15:36:24] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.event.CraftEventFactory.handleNonLivingEntityDamageEvent(CraftEventFactory.java:871)
[15:36:24] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.EntityArmorStand.damageEntity(EntityArmorStand.java:425)
[15:36:24] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.entity.CraftLivingEntity.damage(CraftLivingEntity.java:274)
[15:36:24] [Server thread/WARN]: 	at com.magmaguy.elitemobs.events.BossSpecialAttackDamage.dealSpecialDamage(BossSpecialAttackDamage.java:23)
[15:36:24] [Server thread/WARN]: 	at com.magmaguy.elitemobs.items.customenchantments.FlamethrowerEnchantment.doDamage(FlamethrowerEnchantment.java:50)
[15:36:24] [Server thread/WARN]: 	at com.magmaguy.elitemobs.items.customenchantments.FlamethrowerEnchantment.access$400(FlamethrowerEnchantment.java:25)
[15:36:24] [Server thread/WARN]: 	at com.magmaguy.elitemobs.items.customenchantments.FlamethrowerEnchantment$FlamethrowerEnchantmentEvents$2.run(FlamethrowerEnchantment.java:133)
[15:36:24] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:84)
[15:36:24] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:449)
[15:36:24] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1023)
[15:36:24] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:440)
[15:36:24] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:953)
[15:36:24] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:850)
[15:36:24] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)
`

**Comment by MagmaGuy** [comment]
Seems like this is a CoreProtect error, not an EliteMobs error.
