### ISSUE TITLE
Error (Console)

### ISSUE THREAD

**Issue by GripyCZ** [MagmaGuy/EliteMobs#26]
[21:56:53 ERROR]: Could not pass event CreatureSpawnEvent to EliteMobs v7.1.0
java.lang.NullPointerException: null
at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:770) ~[patched_1.15.2.jar:git-Paper-118]
at com.sk89q.worldguard.WorldGuard.getPlatform(WorldGuard.java:100) ~[?:?]
at com.magmaguy.elitemobs.worldguard.WorldGuardFlagChecker.checkFlag(WorldGuardFlagChecker.java:15) ~[?:?]
at com.magmaguy.elitemobs.worldguard.WorldGuardEliteMobOnlyFlag.onSpawn(WorldGuardEliteMobOnlyFlag.java:17) ~[?:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor357.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.15.2.jar:git-Paper-118]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.15.2.jar:git-Paper-118]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.15.2.jar:git-Paper-118]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:559) ~[patched_1.15.2.jar:git-Paper-118]
at org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.callCreatureSpawnEvent(CraftEventFactory.java:626) ~[patched_1.15.2.jar:git-Paper-118]
at org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.doEntityAddEventCalling(CraftEventFactory.java:547) ~[patched_1.15.2.jar:git-Paper-118]
at net.minecraft.server.v1_15_R1.WorldServer.addEntity0(WorldServer.java:1214) ~[patched_1.15.2.jar:git-Paper-118]
at net.minecraft.server.v1_15_R1.WorldServer.addEntity(WorldServer.java:1121) ~[patched_1.15.2.jar:git-Paper-118]
at org.bukkit.craftbukkit.v1_15_R1.CraftWorld.addEntity(CraftWorld.java:1930) ~[patched_1.15.2.jar:git-Paper-118]
at org.bukkit.craftbukkit.v1_15_R1.CraftWorld.spawn(CraftWorld.java:1937) ~[patched_1.15.2.jar:git-Paper-118]
at org.bukkit.craftbukkit.v1_15_R1.CraftWorld.spawn(CraftWorld.java:1521) ~[patched_1.15.2.jar:git-Paper-118]
at org.bukkit.craftbukkit.v1_15_R1.CraftWorld.spawnEntity(CraftWorld.java:747) ~[patched_1.15.2.jar:git-Paper-118]
at com.magmaguy.elitemobs.npcs.NPCEntity.initializeRole(NPCEntity.java:181) ~[?:?]
at com.magmaguy.elitemobs.npcs.NPCEntity.<init>(NPCEntity.java:101) ~[?:?]
at com.magmaguy.elitemobs.npcs.NPCInitializer.<init>(NPCInitializer.java:15) ~[?:?]
at com.magmaguy.elitemobs.EliteMobs.onEnable(EliteMobs.java:132) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.15.2.jar:git-Paper-118]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) ~[patched_1.15.2.jar:git-Paper-118]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:435) ~[patched_1.15.2.jar:git-Paper-118]
at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:470) ~[patched_1.15.2.jar:git-Paper-118]
at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:384) ~[patched_1.15.2.jar:git-Paper-118]
at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:482) ~[patched_1.15.2.jar:git-Paper-118]
at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:298) ~[patched_1.15.2.jar:git-Paper-118]
at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:885) ~[patched_1.15.2.jar:git-Paper-118]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]

Thanks for help <3  - Gripy

**Comment by MagmaGuy** [comment]
Did this get fixed after a restart?

**Comment by GripyCZ** [comment]
Nope

**Comment by MagmaGuy** [comment]
I think I already resolved this one for the current dev build, it will go public soon (you can get it from discord). Let me know if it still happens then.

**Comment by mitchngwen** [comment]
It's happening again I think:




```
[20:59:21 ERROR]: Could not pass event CreatureSpawnEvent to EliteMobs v8.7.6
java.lang.IllegalArgumentException: Health value (35.0) must be between 0 and 26.809999465942383. (attribute base value: 35.0)
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:482) ~[guava-32.1.2-jre.jar:?]
        at org.bukkit.craftbukkit.v1_20_R3.entity.CraftLivingEntity.setHealth(CraftLivingEntity.java:107) ~[purpur-1.20.4.jar:git-Purpur-2162]
        at com.magmaguy.elitemobs.mobconstructor.EliteEntity.setMaxHealth(EliteEntity.java:321) ~[EliteMobs8.7.7.jar:?]
        at com.magmaguy.elitemobs.mobconstructor.EliteEntity.setLivingEntity(EliteEntity.java:297) ~[EliteMobs8.7.7.jar:?]
        at com.magmaguy.elitemobs.mobconstructor.EliteEntity.<init>(EliteEntity.java:155) ~[EliteMobs8.7.7.jar:?]
        at com.magmaguy.elitemobs.mobspawning.NaturalMobSpawnEventHandler.onSpawn(NaturalMobSpawnEventHandler.java:173) ~[EliteMobs8.7.7.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor680.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:git-Purpur-2162]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[purpur-1.20.4.jar:git-Purpur-2162]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[purpur-1.20.4.jar:git-Purpur-2162]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:617) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R3.event.CraftEventFactory.callCreatureSpawnEvent(CraftEventFactory.java:798) ~[purpur-1.20.4.jar:git-Purpur-2162]
        at org.bukkit.craftbukkit.v1_20_R3.event.CraftEventFactory.doEntityAddEventCalling(CraftEventFactory.java:702) ~[purpur-1.20.4.jar:git-Purpur-2162]
        at net.minecraft.server.level.ServerLevel.addEntity(ServerLevel.java:1782) ~[?:?]
        at net.minecraft.server.level.ServerLevel.addFreshEntity(ServerLevel.java:1704) ~[?:?]
        at net.minecraft.world.level.ServerLevelAccessor.lambda$addFreshEntityWithPassengers$0(ServerLevelAccessor.java:16) ~[?:?]
        at java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:411) ~[?:?]
        at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762) ~[?:?]
        at net.minecraft.world.level.ServerLevelAccessor.addFreshEntityWithPassengers(ServerLevelAccessor.java:16) ~[?:?]
        at net.minecraft.world.level.NaturalSpawner.spawnCategoryForPosition(NaturalSpawner.java:301) ~[?:?]
        at net.minecraft.world.level.NaturalSpawner.spawnCategoryForChunk(NaturalSpawner.java:212) ~[?:?]
        at net.minecraft.world.level.NaturalSpawner.spawnForChunk(NaturalSpawner.java:182) ~[?:?]
        at net.minecraft.server.level.ServerChunkCache.tickChunks(ServerChunkCache.java:645) ~[?:?]
        at net.minecraft.server.level.ServerChunkCache.tick(ServerChunkCache.java:491) ~[?:?]
        at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:889) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1759) ~[purpur-1.20.4.jar:git-Purpur-2162]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:487) ~[purpur-1.20.4.jar:git-Purpur-2162]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1558) ~[purpur-1.20.4.jar:git-Purpur-2162]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1246) ~[purpur-1.20.4.jar:git-Purpur-2162]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[purpur-1.20.4.jar:git-Purpur-2162]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]
```
