### ISSUE TITLE
Could not pass event InventoryClickEvent to EliteMobs v7.1.0

### ISSUE THREAD

**Issue by huzion** [MagmaGuy/EliteMobs#27]
OS: Debian 9 x64
CPU: 1G
Memery: 2G
Server: Paper-1.14.4-b243.jar
Client: Minecraft 1.14.4 Optifine + forge 

------------------
And, I used the Chinese branch form the repo of "EliteMobs-Translation"
------------------

start.sh

```
#!/bin/bash
java -Xms1280M -Xmx1280M -XX:-UseConcMarkSweepGC -XX:-UseGCOverheadLimit -XX:+AlwaysPreTouch -XX:+AggressiveOpts -XX:+UseCompressedOops -jar Paper-1.14.4-b243.jar
```

Plugins:

```
AConomy.jar
Coins.jar
EssentialsXProtect-2.17.1.0.jar
InvisibleArmor.jar
mcMMO-2.1.116.jar
Residence4.8.8.2.jar
Vault.jar
worldguard-bukkit-7.0.2.jar
AntiCreeper.jar
EliteMobs.jar
EssentialsXSpawn-2.17.1.0.jar
LockettePro-2.9.10.jar
ProtocolLib.jar
SkinsRestorer.jar
VeinMiner-1.14.0.jar
AuthMe-5.6.0-SNAPSHOT.jar
EssentialsX-2.17.1.0.jar
expbank-6.0.0.jar
LuckPerms-Bukkit-5.0.72.jar
QuickShop-3.1.4.15.jar
TreeAssist.jar
worldedit-bukkit-7.0.1.jar
```

Server code:

```
[01:25:43] [Server thread/INFO]: huzi issued server command: /em quest
[01:25:45] [Server thread/ERROR]: Could not pass event InventoryClickEvent to EliteMobs v7.1.0
java.lang.ArrayIndexOutOfBoundsException: -1
        at java.util.ArrayList.elementData(ArrayList.java:422) ~[?:1.8.0_232]
        at java.util.ArrayList.get(ArrayList.java:435) ~[?:1.8.0_232]
        at com.magmaguy.elitemobs.quests.QuestsMenu.onTierQuestClick(QuestsMenu.java:101) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor301.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[Paper-1.14.4-b243.jar:git-Paper-243]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[Paper-1.14.4-b243.jar:git-Paper-243]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[Paper-1.14.4-b243.jar:git-Paper-243]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:545) ~[Paper-1.14.4-b243.jar:git-Paper-243]
        at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:2314) ~[Paper-1.14.4-b243.jar:git-Paper-243]
        at net.minecraft.server.v1_14_R1.PacketPlayInWindowClick.a(SourceFile:33) ~[Paper-1.14.4-b243.jar:git-Paper-243]
        at net.minecraft.server.v1_14_R1.PacketPlayInWindowClick.a(SourceFile:10) ~[Paper-1.14.4-b243.jar:git-Paper-243]
        at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[Paper-1.14.4-b243.jar:git-Paper-243]
        at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) ~[Paper-1.14.4-b243.jar:git-Paper-243]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[Paper-1.14.4-b243.jar:git-Paper-243]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[Paper-1.14.4-b243.jar:git-Paper-243]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[Paper-1.14.4-b243.jar:git-Paper-243]
        at net.minecraft.server.v1_14_R1.MinecraftServer.aX(MinecraftServer.java:1029) ~[Paper-1.14.4-b243.jar:git-Paper-243]
        at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:1022) ~[Paper-1.14.4-b243.jar:git-Paper-243]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[Paper-1.14.4-b243.jar:git-Paper-243]
        at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1006) ~[Paper-1.14.4-b243.jar:git-Paper-243]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:929) ~[Paper-1.14.4-b243.jar:git-Paper-243]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_232]
[01:26:36] [Server thread/INFO]: huzi issued server command: /em quest
[01:26:37] [Server thread/ERROR]: Could not pass event InventoryClickEvent to EliteMobs v7.1.0
java.lang.ArrayIndexOutOfBoundsException: null
[01:26:47] [Server thread/INFO]: huzi issued server command: /em quest
```

**Comment by MagmaGuy** [comment]
Issue is the paper / spigot build used. Updating it seems to fix this issue for everyone.

Sorry for the delay in answering but I've only been able to definitely verify this solution recently.
