### ISSUE TITLE
Some errors

### ISSUE THREAD

**Issue by wzpzw5** [MagmaGuy/EliteMobs#38]
[EliteMobs] Failed to update database value.
[16:45:04 WARN]: [EliteMobs] Failed to update database value.
[16:45:04 WARN]: org.sqlite.SQLiteException: [SQLITE_ERROR] SQL error or missing database (cannot commit - no transaction is active)
[16:45:04 WARN]: [EliteMobs] Failed to update database value.
[16:45:04 WARN]: org.sqlite.SQLiteException: [SQLITE_ERROR] SQL error or missing database (cannot commit - no transaction is active)
[16:45:04 WARN]: org.sqlite.SQLiteException: [SQLITE_ERROR] SQL error or missing database (cannot commit - no transaction is active)

EliteMobs version 7.2.4(current latest development build)

**Comment by MagmaGuy** [comment]
Should be fixed as of 7.2.5 released just now, please report if it's not the case.

**Comment by wzpzw5** [comment]
Thanks.
I have tested it for a moment and maybe it has been fixed.
but 
[NAN-HEALTH] a022c215-5388-4a22-8fd0-14f547615f67 had NaN health set

**Comment by wzpzw5** [comment]
[EliteMobs] Failed to get integer value from database!
[17:01:54 WARN]: java.sql.SQLException: ResultSet closed
[17:01:54 ERROR]: Could not pass event PlayerJoinEvent to EliteMobs v7.2.5
java.lang.NullPointerException: null
        at com.magmaguy.elitemobs.playerdata.PlayerData.getActiveGuildLevel(PlayerData.java:122) ~[?:?]
        at com.magmaguy.elitemobs.adventurersguild.GuildRank.getActiveGuildRank(GuildRank.java:46) ~[?:?]
        at com.magmaguy.elitemobs.adventurersguild.GuildRank$GuildRankEvents.onPlayerLogin(GuildRank.java:217) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor2297.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.4.jar:git-Paper-284]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.4.jar:git-Paper-284]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.4.jar:git-Paper-284]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.4.jar:git-Paper-284]
        at net.minecraft.server.v1_16_R3.PlayerList.postChunkLoadJoin(PlayerList.java:273) ~[patched_1.16.4.jar:git-Paper-284]
        at net.minecraft.server.v1_16_R3.PlayerList.lambda$null$1(PlayerList.java:220) ~[patched_1.16.4.jar:git-Paper-284]
        at net.minecraft.server.v1_16_R3.PlayerConnection.tick(PlayerConnection.java:165) ~[?:git-Paper-284]
        at net.minecraft.server.v1_16_R3.NetworkManager.a(NetworkManager.java:388) ~[patched_1.16.4.jar:git-Paper-284]
        at net.minecraft.server.v1_16_R3.ServerConnection.c(ServerConnection.java:145) ~[patched_1.16.4.jar:git-Paper-284]
        at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1384) ~[patched_1.16.4.jar:git-Paper-284]
        at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:377) ~[patched_1.16.4.jar:git-Paper-284]
        at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1212) ~[patched_1.16.4.jar:git-Paper-284]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1000) ~[patched_1.16.4.jar:git-Paper-284]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.4.jar:git-Paper-284]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_271]

**Comment by wzpzw5** [comment]
after restarting the server this bug may be fixed.but
[10:38:04 ERROR]: Could not pass event EliteMobDeathEvent to EliteMobs v7.2.5
java.lang.NullPointerException: null
        at com.magmaguy.elitemobs.items.LootTables.dropWeighedFixedItem(LootTables.java:188) ~[?:?]
        at com.magmaguy.elitemobs.items.LootTables.generateLoot(LootTables.java:142) ~[?:?]
        at com.magmaguy.elitemobs.items.LootTables.generatePlayerLoot(LootTables.java:70) ~[?:?]
        at com.magmaguy.elitemobs.items.LootTables.onDeath(LootTables.java:43) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor812.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.4.jar:git-Paper-284]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[patched_1.16.4.jar:git-Paper-284]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.4.jar:git-Paper-284]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.4.jar:git-Paper-284]
        at com.magmaguy.elitemobs.api.EliteMobDeathEvent$EliteMobDeathEventFilter.onMobDeath(EliteMobDeathEvent.java:55) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor735.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.4.jar:git-Paper-284]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[patched_1.16.4.jar:git-Paper-284]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.4.jar:git-Paper-284]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.4.jar:git-Paper-284]
        at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callEntityDeathEvent(CraftEventFactory.java:801) ~[patched_1.16.4.jar:git-Paper-284]
        at net.minecraft.server.v1_16_R3.EntityLiving.d(EntityLiving.java:1491) ~[patched_1.16.4.jar:git-Paper-284]
        at net.minecraft.server.v1_16_R3.EntityLiving.die(EntityLiving.java:1420) ~[patched_1.16.4.jar:git-Paper-284]
        at net.minecraft.server.v1_16_R3.EntityLiving.damageEntity(EntityLiving.java:1262) ~[patched_1.16.4.jar:git-Paper-284]
        at net.minecraft.server.v1_16_R3.EntityMonster.damageEntity(EntityMonster.java:52) ~[patched_1.16.4.jar:git-Paper-284]
        at net.minecraft.server.v1_16_R3.EntityZombie.damageEntity(EntityZombie.java:250) ~[patched_1.16.4.jar:git-Paper-284]
        at net.minecraft.server.v1_16_R3.EntityHuman.attack(EntityHuman.java:1087) ~[patched_1.16.4.jar:git-Paper-284]
        at net.minecraft.server.v1_16_R3.EntityPlayer.attack(EntityPlayer.java:1832) ~[patched_1.16.4.jar:git-Paper-284]
        at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:2236) ~[?:git-Paper-284]
        at net.minecraft.server.v1_16_R3.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:49) ~[patched_1.16.4.jar:git-Paper-284]
        at net.minecraft.server.v1_16_R3.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:6) ~[patched_1.16.4.jar:git-Paper-284]
        at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23) ~[patched_1.16.4.jar:git-Paper-284]
        at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.4.jar:git-Paper-284]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.4.jar:git-Paper-284]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.4.jar:git-Paper-284]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.4.jar:git-Paper-284]
        at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1136) ~[patched_1.16.4.jar:git-Paper-284]
        at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1129) ~[patched_1.16.4.jar:git-Paper-284]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.4.jar:git-Paper-284]
        at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1090) ~[patched_1.16.4.jar:git-Paper-284]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1004) ~[patched_1.16.4.jar:git-Paper-284]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.4.jar:git-Paper-284]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_271]

**Comment by wzpzw5** [comment]
I will try 7.2.7

**Comment by wzpzw5** [comment]
some errors happed on player first join the server.But it may be caused by the database that exists before and sometimes it isn't happen.

**Comment by wzpzw5** [comment]
[09:13:40 WARN]: [EliteMobs] Failed to get integer value from database!
[09:13:40 WARN]: java.sql.SQLException: ResultSet closed
[09:13:40 ERROR]: Could not pass event PlayerJoinEvent to EliteMobs v7.2.8
java.lang.NullPointerException: null
        at com.magmaguy.elitemobs.playerdata.PlayerData.getActiveGuildLevel(PlayerData.java:122) ~[?:?]
        at com.magmaguy.elitemobs.adventurersguild.GuildRank.getActiveGuildRank(GuildRank.java:46) ~[?:?]
        at com.magmaguy.elitemobs.adventurersguild.GuildRank$GuildRankEvents.onPlayerLogin(GuildRank.java:217) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor766.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.4.jar:git-Tuinity-"ed9e0c4"]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[patched_1.16.4.jar:git-Tuinity-"ed9e0c4"]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.4.jar:git-Tuinity-"ed9e0c4"]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.4.jar:git-Tuinity-"ed9e0c4"]
        at net.minecraft.server.v1_16_R3.PlayerList.postChunkLoadJoin(PlayerList.java:273) ~[patched_1.16.4.jar:git-Tuinity-"ed9e0c4"]
        at net.minecraft.server.v1_16_R3.PlayerList.lambda$null$1(PlayerList.java:220) ~[patched_1.16.4.jar:git-Tuinity-"ed9e0c4"]
        at net.minecraft.server.v1_16_R3.PlayerConnection.tick(PlayerConnection.java:165) ~[?:git-Tuinity-"ed9e0c4"]
        at net.minecraft.server.v1_16_R3.NetworkManager.a(NetworkManager.java:535) ~[patched_1.16.4.jar:git-Tuinity-"ed9e0c4"]
        at net.minecraft.server.v1_16_R3.ServerConnection.c(ServerConnection.java:150) ~[patched_1.16.4.jar:git-Tuinity-"ed9e0c4"]
        at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1446) ~[patched_1.16.4.jar:git-Tuinity-"ed9e0c4"]
        at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:378) ~[patched_1.16.4.jar:git-Tuinity-"ed9e0c4"]
        at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1271) ~[patched_1.16.4.jar:git-Tuinity-"ed9e0c4"]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1003) ~[patched_1.16.4.jar:git-Tuinity-"ed9e0c4"]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:178) ~[patched_1.16.4.jar:git-Tuinity-"ed9e0c4"]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_271]

**Comment by wzpzw5** [comment]
on player first join the server.

**Comment by MagmaGuy** [comment]
I believe I've fixed them for the upcoming release. Also I'll just point out that I am not very quick to reply on github, but I usually reply immediately on Discord.

**Comment by wzpzw5** [comment]
[EliteMobs] Failed to get integer value from database!
[15:49:22 WARN]: java.sql.SQLException: ResultSet closed
[15:49:22 ERROR]: Could not pass event PlayerJoinEvent to EliteMobs v7.2.9
java.lang.NullPointerException: null
        at com.magmaguy.elitemobs.playerdata.PlayerData.getActiveGuildLevel(PlayerData.java:122) ~[?:?]
        at com.magmaguy.elitemobs.adventurersguild.GuildRank.getActiveGuildRank(GuildRank.java:46) ~[?:?]
        at com.magmaguy.elitemobs.adventurersguild.GuildRank$GuildRankEvents.onPlayerLogin(GuildRank.java:217) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor635.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.4.jar:git-Tuinity-"8056d13"]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.4.jar:git-Tuinity-"8056d13"]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.4.jar:git-Tuinity-"8056d13"]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.4.jar:git-Tuinity-"8056d13"]
        at net.minecraft.server.v1_16_R3.PlayerList.postChunkLoadJoin(PlayerList.java:273) ~[patched_1.16.4.jar:git-Tuinity-"8056d13"]
        at net.minecraft.server.v1_16_R3.PlayerList.lambda$null$1(PlayerList.java:220) ~[patched_1.16.4.jar:git-Tuinity-"8056d13"]
        at net.minecraft.server.v1_16_R3.PlayerConnection.tick(PlayerConnection.java:165) ~[?:git-Tuinity-"8056d13"]
        at net.minecraft.server.v1_16_R3.NetworkManager.a(NetworkManager.java:538) ~[patched_1.16.4.jar:git-Tuinity-"8056d13"]
        at net.minecraft.server.v1_16_R3.ServerConnection.c(ServerConnection.java:150) ~[patched_1.16.4.jar:git-Tuinity-"8056d13"]
        at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1446) ~[patched_1.16.4.jar:git-Tuinity-"8056d13"]
        at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:378) ~[patched_1.16.4.jar:git-Tuinity-"8056d13"]
        at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1271) ~[patched_1.16.4.jar:git-Tuinity-"8056d13"]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1003) ~[patched_1.16.4.jar:git-Tuinity-"8056d13"]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:178) ~[patched_1.16.4.jar:git-Tuinity-"8056d13"]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_271]

**Comment by wzpzw5** [comment]
still on player first join

**Comment by MagmaGuy** [comment]
Ok I finally nailed the issue down, it should really be good to go from the next version on.

**Comment by wzpzw5** [comment]
OK. They were fixed.
Thanks.
