### ISSUE TITLE
Errors with npcs

### ISSUE THREAD

**Issue by ChrisTVH** [MagmaGuy/EliteMobs#49]
In the stable version the published after a good time the npcs disappear, however when you upgrade to the beta version the npc back_teleporter.yml returns this error message:
```bash
java.lang.IllegalArgumentException: Cannot translate null text
        at org.apache.commons.lang.Validate.notNull(Validate.java:192) ~[patched_1.16.5.jar:git-Paper-466]
        at org.bukkit.ChatColor.translateAlternateColorCodes(ChatColor.java:354) ~[patched_1.16.5.jar:git-Paper-466]
        at com.magmaguy.elitemobs.ChatColorConverter.convert(ChatColorConverter.java:14) ~[?:?]
        at com.magmaguy.elitemobs.npcs.NPCInteractions.playerNPCInteract(NPCInteractions.java:111) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor716.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.5.jar:git-Paper-466]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.5.jar:git-Paper-466]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Paper-466]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.5.jar:git-Paper-466]
        at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:2196) ~[patched_1.16.5.jar:git-Paper-466]
        at net.minecraft.server.v1_16_R3.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:49) ~[patched_1.16.5.jar:git-Paper-466]
        at net.minecraft.server.v1_16_R3.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:6) ~[patched_1.16.5.jar:git-Paper-466]
        at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23) ~[patched_1.16.5.jar:git-Paper-466]
        at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.5.jar:git-Paper-466]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.5.jar:git-Paper-466]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.5.jar:git-Paper-466]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.5.jar:git-Paper-466]
        at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1133) ~[patched_1.16.5.jar:git-Paper-466]
        at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1126) ~[patched_1.16.5.jar:git-Paper-466]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.5.jar:git-Paper-466]
        at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1087) ~[patched_1.16.5.jar:git-Paper-466]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1001) ~[patched_1.16.5.jar:git-Paper-466]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:174) ~[patched_1.16.5.jar:git-Paper-466]
        at java.lang.Thread.run(Thread.java:834) [?:?]
````
Also when restarting the npcs disappear or when doing /em reload and do not come out in their defined positions and the npc travelling_merchant.yml does not appear to you their role.

```bash
[16:17:31 INFO]: This server is running Paper version git-Paper-466 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
[16:17:31 INFO]: Checking version, please wait...
[16:17:31 INFO]: Previous version: git-Paper-437 (MC: 1.16.5)
[16:17:31 INFO]: You are running the latest version
[EliteMobs] version 7.2.34
```

**Comment by MagmaGuy** [comment]
Fixed by 7.2.35. Thank you for the report.
