### ISSUE TITLE
Error keep spamming on console

### ISSUE THREAD

**Issue by apatuka** [MagmaGuy/EliteMobs#50]
Hello,

I'm using the **[EliteMobs] version 7.2.39**
Whenever a elitemob dies, it's suppose to calculate the pickWeighedProbability, but it returns null

Here is the error:

`>.... [14:13:34 ERROR]: Could not pass event EliteMobDeathEvent to EliteMobs v7.2.39
java.lang.NullPointerException: null
at com.magmaguy.elitemobs.items.LootTables.generateLoot(LootTables.java:149) ~[?:?]
at com.magmaguy.elitemobs.items.LootTables.generateLoot(LootTables.java:117) ~[?:?]
at com.magmaguy.elitemobs.items.LootTables.generatePlayerLoot(LootTables.java:74) ~[?:?]
at com.magmaguy.elitemobs.powers.bosspowers.HyperLoot.onEliteMobDeath(HyperLoot.java:20) ~[?:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor904.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.5.jar:git-Purpur-982]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.5.jar:git-Purpur-982]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Purpur-982]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.5.jar:git-Purpur-982]
at com.magmaguy.elitemobs.utils.EventCaller.<init>(EventCaller.java:8) ~[?:?]
at com.magmaguy.elitemobs.api.EliteMobDeathEvent$EliteMobDeathEventFilter.onMobDeath(EliteMobDeathEvent.java:53) ~[?:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor849.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.5.jar:git-Purpur-982]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.5.jar:git-Purpur-982]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Purpur-982]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.5.jar:git-Purpur-982]
at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callEntityDeathEvent(CraftEventFactory.java:838) ~[patched_1.16.5.jar:git-Purpur-982]
at net.minecraft.server.v1_16_R3.EntityLiving.d(EntityLiving.java:1524) ~[patched_1.16.5.jar:git-Purpur-982]
at net.minecraft.server.v1_16_R3.EntityLiving.die(EntityLiving.java:1444) ~[patched_1.16.5.jar:git-Purpur-982]
at net.minecraft.server.v1_16_R3.EntityLiving.damageEntity(EntityLiving.java:1273) ~[patched_1.16.5.jar:git-Purpur-982]
at net.minecraft.server.v1_16_R3.EntityInsentient.damageEntity(EntityInsentient.java:279) ~[patched_1.16.5.jar:git-Purpur-982]
at net.minecraft.server.v1_16_R3.EntityMonster.damageEntity(EntityMonster.java:52) ~[patched_1.16.5.jar:git-Purpur-982]
at net.minecraft.server.v1_16_R3.EntityHuman.attack(EntityHuman.java:1108) ~[patched_1.16.5.jar:git-Purpur-982]
at net.minecraft.server.v1_16_R3.EntityPlayer.attack(EntityPlayer.java:2133) ~[patched_1.16.5.jar:git-Purpur-982]
at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:2372) ~[patched_1.16.5.jar:git-Purpur-982]
at net.minecraft.server.v1_16_R3.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:49) ~[patched_1.16.5.jar:git-Purpur-982]
at net.minecraft.server.v1_16_R3.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:6) ~[patched_1.16.5.jar:git-Purpur-982]
at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:43) ~[patched_1.16.5.jar:git-Purpur-982]
at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.5.jar:git-Purpur-982]
at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.5.jar:git-Purpur-982]
at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.5.jar:git-Purpur-982]
at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.5.jar:git-Purpur-982]
at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1207) ~[patched_1.16.5.jar:git-Purpur-982]
at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1200) ~[patched_1.16.5.jar:git-Purpur-982]
at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.5.jar:git-Purpur-982]
at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1176) ~[patched_1.16.5.jar:git-Purpur-982]
at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1020) ~[patched_1.16.5.jar:git-Purpur-982]
at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:176) ~[patched_1.16.5.jar:git-Purpur-982]
at java.lang.Thread.run(Thread.java:834) [?:?] `

**Comment by MagmaGuy** [comment]
Did you disable specific loot types?

**Comment by apatuka** [comment]
I have
doEliteMobsLoot: false

Because i want to use the specific loot from custom bossess and prevent random items generated by just killing mobs.

**Comment by MagmaGuy** [comment]
That's not what that does, what you did completely deletes all drop types for elites.

That also means that players will never be able to get out of tier ~15, out of the 200 tiers in EliteMobs.

I'll patch the error but realistically your current setup will prevent anyone in your server from progressing.

**Comment by MagmaGuy** [comment]
This has been patched since.
