### ISSUE TITLE
NPE on damage event

### ISSUE THREAD

**Issue by RoboMWM** [MagmaGuy/EliteMobs#6]
Remember, plugins can modify the death message, which includes making it null. If that's what you're acting on. As this happened on the second death of a player fighting a goblin

```
[20:27:20] [Server thread/ERROR]: Could not pass event EntityDamageByEntityEvent to EliteMobs v6.2.0
org.bukkit.event.EventException: null
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:72) ~[patched_1.12.2.jar:git-Paper-1373]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.12.2.jar:git-Paper-1373]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.12.2.jar:git-Paper-1373]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:515) [patched_1.12.2.jar:git-Paper-1373]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:500) [patched_1.12.2.jar:git-Paper-1373]
	at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callEvent(CraftEventFactory.java:94) [patched_1.12.2.jar:git-Paper-1373]
	at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:581) [patched_1.12.2.jar:git-Paper-1373]
	at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:484) [patched_1.12.2.jar:git-Paper-1373]
	at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:613) [patched_1.12.2.jar:git-Paper-1373]
	at net.minecraft.server.v1_12_R1.EntityLiving.damageEntity0(EntityLiving.java:1369) [patched_1.12.2.jar:git-Paper-1373]
	at net.minecraft.server.v1_12_R1.EntityHuman.damageEntity0(EntityHuman.java:853) [patched_1.12.2.jar:git-Paper-1373]
	at net.minecraft.server.v1_12_R1.EntityLiving.damageEntity(EntityLiving.java:887) [patched_1.12.2.jar:git-Paper-1373]
	at net.minecraft.server.v1_12_R1.EntityHuman.damageEntity(EntityHuman.java:766) [patched_1.12.2.jar:git-Paper-1373]
	at net.minecraft.server.v1_12_R1.EntityPlayer.damageEntity(EntityPlayer.java:612) [patched_1.12.2.jar:git-Paper-1373]
	at net.minecraft.server.v1_12_R1.EntityMonster.B(EntityMonster.java:68) [patched_1.12.2.jar:git-Paper-1373]
	at net.minecraft.server.v1_12_R1.EntityZombie.B(EntityZombie.java:202) [patched_1.12.2.jar:git-Paper-1373]
	at net.minecraft.server.v1_12_R1.PathfinderGoalMeleeAttack.a(SourceFile:127) [patched_1.12.2.jar:git-Paper-1373]
	at net.minecraft.server.v1_12_R1.PathfinderGoalMeleeAttack.e(SourceFile:119) [patched_1.12.2.jar:git-Paper-1373]
	at net.minecraft.server.v1_12_R1.PathfinderGoalZombieAttack.e(SourceFile:28) [patched_1.12.2.jar:git-Paper-1373]
	at net.minecraft.server.v1_12_R1.PathfinderGoalSelector.a(SourceFile:129) [patched_1.12.2.jar:git-Paper-1373]
	at net.minecraft.server.v1_12_R1.EntityInsentient.doTick(EntityInsentient.java:677) [patched_1.12.2.jar:git-Paper-1373]
	at net.minecraft.server.v1_12_R1.EntityLiving.n(EntityLiving.java:2123) [patched_1.12.2.jar:git-Paper-1373]
	at net.minecraft.server.v1_12_R1.EntityInsentient.n(EntityInsentient.java:508) [patched_1.12.2.jar:git-Paper-1373]
	at net.minecraft.server.v1_12_R1.EntityMonster.n(EntityMonster.java:24) [patched_1.12.2.jar:git-Paper-1373]
	at net.minecraft.server.v1_12_R1.EntityZombie.n(EntityZombie.java:155) [patched_1.12.2.jar:git-Paper-1373]
	at net.minecraft.server.v1_12_R1.EntityLiving.B_(EntityLiving.java:1976) [patched_1.12.2.jar:git-Paper-1373]
	at net.minecraft.server.v1_12_R1.EntityInsentient.B_(EntityInsentient.java:247) [patched_1.12.2.jar:git-Paper-1373]
	at net.minecraft.server.v1_12_R1.EntityMonster.B_(EntityMonster.java:28) [patched_1.12.2.jar:git-Paper-1373]
	at net.minecraft.server.v1_12_R1.World.entityJoinedWorld(World.java:1771) [patched_1.12.2.jar:git-Paper-1373]
	at net.minecraft.server.v1_12_R1.World.h(World.java:1741) [patched_1.12.2.jar:git-Paper-1373]
	at net.minecraft.server.v1_12_R1.World.tickEntities(World.java:1562) [patched_1.12.2.jar:git-Paper-1373]
	at net.minecraft.server.v1_12_R1.WorldServer.tickEntities(WorldServer.java:675) [patched_1.12.2.jar:git-Paper-1373]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:914) [patched_1.12.2.jar:git-Paper-1373]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:426) [patched_1.12.2.jar:git-Paper-1373]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767) [patched_1.12.2.jar:git-Paper-1373]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665) [patched_1.12.2.jar:git-Paper-1373]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
Caused by: java.lang.NullPointerException
	at java.lang.String.replace(String.java:2240) ~[?:1.8.0_111]
	at com.magmaguy.elitemobs.collateralminecraftchanges.PlayerDeathMessageByEliteMob.deathMessagePlaceholderConversion(PlayerDeathMessageByEliteMob.java:101) ~[?:?]
	at com.magmaguy.elitemobs.collateralminecraftchanges.PlayerDeathMessageByEliteMob.deathMessageSender(PlayerDeathMessageByEliteMob.java:90) ~[?:?]
	at com.magmaguy.elitemobs.collateralminecraftchanges.PlayerDeathMessageByEliteMob.intializeDeathMessage(PlayerDeathMessageByEliteMob.java:67) ~[?:?]
	at com.magmaguy.elitemobs.mobcustomizer.DamageAdjuster.eliteMobDamageHandler(DamageAdjuster.java:191) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor733.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[patched_1.12.2.jar:git-Paper-1373]
	... 36 more
```

**Comment by MagmaGuy** [comment]
That was one of the first things that I resolved for 6.2.1. The custom death messages weren't ready for the custom bosses upon release of 6.2, it was an oversight on my end.
