### ISSUE TITLE
[EliteMobs] Something went wrong while generating a new player entry. This is bad! Tell the dev.

### ISSUE THREAD

**Issue by yuankun1** [MagmaGuy/EliteMobs#61]
[14:48:27 WARN]: [EliteMobs] Something went wrong while generating a new player entry. This is bad! Tell the dev.
[14:48:27 WARN]: java.lang.NullPointerException: Cannot invoke "org.bukkit.entity.Player.getName()" because the return value of "org.bukkit.Bukkit.getPlayer(java.util.UUID)" is null
[14:48:27 WARN]: [EliteMobs] No player entry detected, generating new entry!

**Comment by yuankun1** [comment]
[15:20:03 WARN]: [EliteMobs] Task #3041977 for EliteMobs v7.3.2 generated an exception
java.lang.IllegalArgumentException: x not finite
        at org.bukkit.util.NumberConversions.checkFinite(NumberConversions.java:118) ~[patched_1.16.5.jar:git-Paper-778]
        at org.bukkit.util.Vector.checkFinite(Vector.java:814) ~[patched_1.16.5.jar:git-Paper-778]
        at org.bukkit.craftbukkit.v1_16_R3.entity.CraftEntity.setVelocity(CraftEntity.java:430) ~[patched_1.16.5.jar:git-Paper-778]
        at com.magmaguy.elitemobs.powers.miscellaneouspowers.GroundPound$2$1.run(GroundPound.java:86) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100) ~[patched_1.16.5.jar:git-Paper-778]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.16.5.jar:git-Paper-778]
        at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1427) ~[patched_1.16.5.jar:git-Paper-778]
        at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:436) ~[patched_1.16.5.jar:git-Paper-778]
        at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1342) ~[patched_1.16.5.jar:git-Paper-778]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1130) ~[patched_1.16.5.jar:git-Paper-778]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Paper-778]

**Comment by MagmaGuy** [comment]
Fixes were implemented, let me know if it happens again.
