### ISSUE TITLE
Error when player join

### ISSUE THREAD

**Issue by mcdudu233** [MagmaGuy/EliteMobs#65]
Could not pass event PlayerJoinEvent to EliteMobs v7.3.3
java.lang.NoSuchMethodError: us/myles/ViaVersion/api/Via.getManager()Lus/myles/ViaVersion/ViaManager; (loaded from file:/C:/tkzd/plugins/ViaVersion-4.0.1.jar by PluginClassLoader{plugin=ViaVersion v4.0.1, pluginEnabled=true, url=plugins\ViaVersion-4.0.1.jar}) called from class com.magmaguy.shaded.adventure-platform-bukkit.adventure.platform.bukkit.BukkitFacet$ViaHook (loaded from file:/C:/tkzd/plugins/EliteMobs.jar by PluginClassLoader{plugin=EliteMobs v7.3.3, pluginEnabled=true, url=plugins\EliteMobs.jar}).
        at com.magmaguy.shaded.adventure-platform-bukkit.adventure.platform.bukkit.BukkitFacet$ViaHook.apply(BukkitFacet.java:347) ~[?:?]
        at com.magmaguy.shaded.adventure-platform-bukkit.adventure.platform.bukkit.BukkitFacet$ViaHook.apply(BukkitFacet.java:344) ~[?:?]
        at com.magmaguy.shaded.adventure-platform-bukkit.adventure.platform.viaversion.ViaFacet.findConnection(ViaFacet.java:96) ~[?:?]
        at com.magmaguy.shaded.adventure-platform-bukkit.adventure.platform.viaversion.ViaFacet.findProtocol(ViaFacet.java:100) ~[?:?]
        at com.magmaguy.shaded.adventure-platform-bukkit.adventure.platform.viaversion.ViaFacet.isApplicable(ViaFacet.java:92) ~[?:?]
        at com.magmaguy.shaded.adventure-platform-bukkit.adventure.platform.facet.Facet.of(Facet.java:100) ~[?:?]
        at com.magmaguy.shaded.adventure-platform-bukkit.adventure.platform.facet.FacetAudience.<init>(FacetAudience.java:109) ~[?:?]
        at com.magmaguy.shaded.adventure-platform-bukkit.adventure.platform.bukkit.BukkitAudience.<init>(BukkitAudience.java:85) ~[?:?]
        at com.magmaguy.shaded.adventure-platform-bukkit.adventure.platform.bukkit.BukkitAudiencesImpl.createAudience(BukkitAudiencesImpl.java:162) ~[?:?]
        at com.magmaguy.shaded.adventure-platform-bukkit.adventure.platform.bukkit.BukkitAudiencesImpl.createAudience(BukkitAudiencesImpl.java:71) ~[?:?]
        at com.magmaguy.shaded.adventure-platform-bukkit.adventure.platform.facet.FacetAudienceProvider.lambda$addViewer$0(FacetAudienceProvider.java:89) ~[?:?]
        at com.magmaguy.shaded.adventure-platform-bukkit.adventure.platform.facet.FacetAudienceProvider$$Lambda$5514/0x000000001d9ac0b0.apply(Unknown Source) ~[?:?]
        at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1660) ~[?:1.8.0_292]
        at com.magmaguy.shaded.adventure-platform-bukkit.adventure.platform.facet.FacetAudienceProvider.addViewer(FacetAudienceProvider.java:88) ~[?:?]
        at com.magmaguy.shaded.adventure-platform-bukkit.adventure.platform.bukkit.BukkitAudiencesImpl.lambda$new$3(BukkitAudiencesImpl.java:101) ~[?:?]
        at com.magmaguy.shaded.adventure-platform-bukkit.adventure.platform.bukkit.BukkitAudiencesImpl$$Lambda$5515/0x000000001d0ba2e0.accept(Unknown Source) ~[?:?]
        at com.magmaguy.shaded.adventure-platform-bukkit.adventure.platform.bukkit.BukkitAudiencesImpl.lambda$registerEvent$5(BukkitAudiencesImpl.java:215) ~[?:?]
        at com.magmaguy.shaded.adventure-platform-bukkit.adventure.platform.bukkit.BukkitAudiencesImpl$$Lambda$5516/0x0000000018511040.execute(Unknown Source) ~[?:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[patched_1.15.2.jar:git-YAPFA-"b08ee86"]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.15.2.jar:git-YAPFA-"b08ee86"]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.15.2.jar:git-YAPFA-"b08ee86"]
        at net.minecraft.server.v1_15_R1.PlayerList.postChunkLoadJoin(PlayerList.java:242) ~[patched_1.15.2.jar:git-YAPFA-"b08ee86"]
        at net.minecraft.server.v1_15_R1.PlayerList.lambda$a$1(PlayerList.java:189) ~[patched_1.15.2.jar:git-YAPFA-"b08ee86"]
        at net.minecraft.server.v1_15_R1.PlayerList$$Lambda$6264/0x000000002c1482c0.run(Unknown Source) ~[?:?]
        at net.minecraft.server.v1_15_R1.PlayerConnection.tick(PlayerConnection.java:150) ~[patched_1.15.2.jar:git-YAPFA-"b08ee86"]
        at net.minecraft.server.v1_15_R1.NetworkManager.a(NetworkManager.java:422) ~[patched_1.15.2.jar:git-YAPFA-"b08ee86"]
        at net.minecraft.server.v1_15_R1.ServerConnection.c(ServerConnection.java:142) ~[patched_1.15.2.jar:git-YAPFA-"b08ee86"]
        at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1420) ~[patched_1.15.2.jar:git-YAPFA-"b08ee86"]
        at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:441) ~[patched_1.15.2.jar:git-YAPFA-"b08ee86"]
        at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1246) ~[patched_1.15.2.jar:git-YAPFA-"b08ee86"]
        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:975) ~[patched_1.15.2.jar:git-YAPFA-"b08ee86"]
        at java.lang.Thread.run(Thread.java:823) [?:1.8.0_292]

and warn when using "/em shop":
[10:24:09 WARN]: java.lang.NullPointerException
[10:24:09 WARN]:        at java.util.concurrent.ConcurrentHashMap.get(ConcurrentHashMap.java:936)
[10:24:09 WARN]:        at net.minecraft.server.v1_15_R1.UserCache.a(UserCache.java:126)
[10:24:09 WARN]:        at net.minecraft.server.v1_15_R1.UserCache.a(UserCache.java:109)
[10:24:09 WARN]:        at net.minecraft.server.v1_15_R1.UserCache.saveProfile(UserCache.java:107)
[10:24:09 WARN]:        at com.destroystokyo.paper.profile.CraftPlayerProfile.complete(CraftPlayerProfile.java:200)
[10:24:09 WARN]:        at net.minecraft.server.v1_15_R1.TileEntitySkull.b(TileEntitySkull.java:227)
[10:24:09 WARN]:        at org.bukkit.craftbukkit.v1_15_R1.inventory.CraftMetaSkull.applyToItem(CraftMetaSkull.java:95)
[10:24:09 WARN]:        at org.bukkit.craftbukkit.v1_15_R1.inventory.CraftItemStack.setItemMeta(CraftItemStack.java:518)
[10:24:09 WARN]:        at org.bukkit.craftbukkit.v1_15_R1.inventory.CraftItemStack.asNMSCopy(CraftItemStack.java:42)
[10:24:09 WARN]:        at org.bukkit.craftbukkit.v1_15_R1.inventory.CraftInventory.setItem(CraftInventory.java:99)
[10:24:09 WARN]:        at com.magmaguy.elitemobs.menus.BuyOrSellMenu.constructBuyOrSellMenu(BuyOrSellMenu.java:23)
[10:24:09 WARN]:        at com.magmaguy.elitemobs.menus.ProceduralShopMenu.shopInitializer(ProceduralShopMenu.java:35)
[10:24:09 WARN]:        at com.magmaguy.elitemobs.commands.UserCommands.lambda$new$2(UserCommands.java:56)
[10:24:09 WARN]:        at com.magmaguy.elitemobs.commands.UserCommands$$Lambda$5640/0x0000000020ed1f40.execute(Unknown Source)
[10:24:09 WARN]:        at com.magmaguy.shaded.cloud.execution.CommandExecutionCoordinator$SimpleCoordinator.coordinateExecution(CommandExecutionCoordinator.java:121)
[10:24:09 WARN]:        at com.magmaguy.shaded.cloud.CommandManager.executeCommand(CommandManager.java:176)
[10:24:09 WARN]:        at com.magmaguy.shaded.cloud.bukkit.BukkitCommand.execute(BukkitCommand.java:91)
[10:24:09 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
[10:24:09 WARN]:        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.dispatchCommand(CraftServer.java:761)
[10:24:09 WARN]:        at net.minecraft.server.v1_15_R1.PlayerConnection.handleCommand(PlayerConnection.java:1880)
[10:24:09 WARN]:        at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1688)
[10:24:09 WARN]:        at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(PacketPlayInChat.java:47)
[10:24:09 WARN]:        at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(PacketPlayInChat.java:5)
[10:24:09 WARN]:        at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:43)
[10:24:09 WARN]:        at net.minecraft.server.v1_15_R1.PlayerConnectionUtils$$Lambda$6330/0x00000000268cd940.run(Unknown Source)
[10:24:09 WARN]:        at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18)
[10:24:09 WARN]:        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136)
[10:24:09 WARN]:        at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
[10:24:09 WARN]:        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109)
[10:24:09 WARN]:        at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:1169)
[10:24:09 WARN]:        at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:1162)
[10:24:09 WARN]:        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeAll(IAsyncTaskHandler.java:95)
[10:24:09 WARN]:        at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1297)
[10:24:09 WARN]:        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:975)
[10:24:09 WARN]:        at java.lang.Thread.run(Thread.java:823)

**Comment by MagmaGuy** [comment]
This is an issue with your configurations, it looks like you don't have valid items for the menus. Reset the menus folder to its defaults to fix it.

**Comment by MagmaGuy** [comment]
The join event error is not EliteMobs fyi, something about ViaVersion is messed up.
