### ISSUE TITLE
java.lang.IllegalArgumentException: Health must be between 0 and 1.0E8, but was 7.0E9. (attribute base value: 7.000000013E9)

### ISSUE THREAD

**Issue by yuankun1** [MagmaGuy/EliteMobs#66]
[16:38:05 WARN]: java.lang.IllegalArgumentException: Health must be between 0 and 1.0E8, but was 7.0E9. (attribute base value: 7.000000013E9)
[16:38:05 WARN]:        at org.bukkit.craftbukkit.v1_17_R1.entity.CraftLivingEntity.setHealth(CraftLivingEntity.java:110)
[16:38:05 WARN]:        at com.magmaguy.elitemobs.mobconstructor.EliteMobEntity.setMaxHealth(EliteMobEntity.java:328)
[16:38:05 WARN]:        at com.magmaguy.elitemobs.mobconstructor.EliteMobEntity.initializeBasicValues(EliteMobEntity.java:267)
[16:38:05 WARN]:        at com.magmaguy.elitemobs.mobconstructor.EliteMobEntity.<init>(EliteMobEntity.java:144)
[16:38:05 WARN]:        at com.magmaguy.elitemobs.mobconstructor.custombosses.CustomBossEntity.<init>(CustomBossEntity.java:207)
[16:38:05 WARN]:        at com.magmaguy.elitemobs.mobconstructor.custombosses.CustomBossEntity.constructCustomBoss(CustomBossEntity.java:99)
[16:38:05 WARN]:        at com.magmaguy.elitemobs.commands.SpawnCommand.spawnCustomBossCommand(SpawnCommand.java:95)
[16:38:05 WARN]:        at com.magmaguy.elitemobs.commands.AdminCommands.lambda$new$15(AdminCommands.java:182)
[16:38:05 WARN]:        at com.magmaguy.shaded.cloud.execution.CommandExecutionCoordinator$SimpleCoordinator.coordinateExecution(CommandExecutionCoordinator.java:121)
[16:38:05 WARN]:        at com.magmaguy.shaded.cloud.CommandManager.executeCommand(CommandManager.java:176)
[16:38:05 WARN]:        at com.magmaguy.shaded.cloud.bukkit.BukkitCommand.execute(BukkitCommand.java:91)
[16:38:05 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
[16:38:05 WARN]:        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchCommand(CraftServer.java:821)
[16:38:05 WARN]:        at net.minecraft.server.network.PlayerConnection.handleCommand(PlayerConnection.java:2170)
[16:38:05 WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1981)
[16:38:05 WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1962)
[16:38:05 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:46)
[16:38:05 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:6)
[16:38:05 WARN]:        at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$1(PlayerConnectionUtils.java:36)
[16:38:05 WARN]:        at net.minecraft.server.TickTask.run(TickTask.java:18)
[16:38:05 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:149)
[16:38:05 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.executeTask(IAsyncTaskHandlerReentrant.java:23)
[16:38:05 WARN]:        at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:1348)
[16:38:05 WARN]:        at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:190)
[16:38:05 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:122)
[16:38:05 WARN]:        at net.minecraft.server.MinecraftServer.bf(MinecraftServer.java:1327)
[16:38:05 WARN]:        at net.minecraft.server.MinecraftServer.executeNext(MinecraftServer.java:1320)
[16:38:05 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:132)
[16:38:05 WARN]:        at net.minecraft.server.MinecraftServer.sleepForTick(MinecraftServer.java:1281)
[16:38:05 WARN]:        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1192)
[16:38:05 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316)
[16:38:05 WARN]:        at java.base/java.lang.Thread.run(Thread.java:831)

**Comment by MagmaGuy** [comment]
I don't know why you're trying to spawn a boss with 700,000,000 health but if you want to do that you'll have to change the max health of your server beyond 10,000,000. Not an EliteMobs bug.
