### ISSUE TITLE
WARN

### ISSUE THREAD

**Issue by benr233** [MagmaGuy/EliteMobs#69]
[17:52:41] [Server thread/WARN]: [EliteMobs] Task #3134980 for EliteMobs v7.3.4 generated an exception
java.lang.NullPointerException: Cannot invoke "org.bukkit.entity.LivingEntity.getHealth()" because "this.livingEntity" is null
	at com.magmaguy.elitemobs.mobconstructor.EliteMobEntity.getHealth(EliteMobEntity.java:352) ~[?:?]
	at com.magmaguy.elitemobs.mobconstructor.custombosses.CustomBossBossBar$1.run(CustomBossBossBar.java:63) ~[?:?]
	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.17.1.jar:git-Paper-112]
	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[patched_1.17.1.jar:git-Paper-112]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1490) ~[patched_1.17.1.jar:git-Paper-112]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:479) ~[patched_1.17.1.jar:git-Paper-112]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1406) ~[patched_1.17.1.jar:git-Paper-112]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1188) ~[patched_1.17.1.jar:git-Paper-112]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[patched_1.17.1.jar:git-Paper-112]
	at java.lang.Thread.run(Thread.java:831) [?:?]

**Comment by MagmaGuy** [comment]
Already fixed for the latest dev version.
