### ISSUE TITLE
java.lang.IllegalArgumentException: x not finite error

### ISSUE THREAD

**Issue by andris155** [MagmaGuy/EliteMobs#78]
```
[10:54:18 ERROR]: Invalid entity rotation: NaN, discarding.
[10:54:18 ERROR]: Invalid entity rotation: NaN, discarding.
[10:54:18 WARN]: [EliteMobs] Task #442641 for EliteMobs v7.3.7 generated an exception
java.lang.IllegalArgumentException: x not finite
        at org.bukkit.util.NumberConversions.checkFinite(NumberConversions.java:118) ~[patched_1.17.1.jar:git-Paper-263]
        at org.bukkit.util.Vector.checkFinite(Vector.java:814) ~[patched_1.17.1.jar:git-Paper-263]
        at org.bukkit.craftbukkit.v1_17_R1.entity.CraftEntity.setVelocity(CraftEntity.java:438) ~[patched_1.17.1.jar:git-Paper-263]
        at com.magmaguy.elitemobs.combatsystem.EliteProjectile.create(EliteProjectile.java:20) ~[EliteMobs.jar:?]
        at com.magmaguy.elitemobs.powers.offensivepowers.AttackFireball.shootFireball(AttackFireball.java:27) ~[EliteMobs.jar:?]
        at com.magmaguy.elitemobs.powers.offensivepowers.AttackFireball$1.run(AttackFireball.java:62) ~[EliteMobs.jar:?]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.17.1.jar:git-Paper-263]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[patched_1.17.1.jar:git-Paper-263]
        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1559) ~[patched_1.17.1.jar:git-Paper-263]
        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:479) ~[patched_1.17.1.jar:git-Paper-263]
        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1475) ~[patched_1.17.1.jar:git-Paper-263]
        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1274) ~[patched_1.17.1.jar:git-Paper-263]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Paper-263]
        at java.lang.Thread.run(Thread.java:831) [?:?]
```
EliteMobs v7.3.7
Paper build 263

**Comment by MagmaGuy** [comment]
This should be fixed.
