### ISSUE TITLE
Bug with Minecraft 1.18

### ISSUE THREAD

**Issue by oraphaleao** [MagmaGuy/EliteMobs#87]
Hello, after update to 1.18 version of Minecraft, this occur frequently...

`java.lang.NullPointerException: Cannot invoke "com.magmaguy.elitemobs.config.customspawns.CustomSpawnConfig.getCustomEvent(String)" because "com.magmaguy.elitemobs.config.customspawns.CustomSpawnConfig.customSpawnConfig" is null
        at com.magmaguy.elitemobs.mobconstructor.CustomSpawn.<init>(CustomSpawn.java:55) ~[?:?]
        at com.magmaguy.elitemobs.events.TimedEvent.instantiateEvent(TimedEvent.java:95) ~[?:?]
        at com.magmaguy.elitemobs.events.TimedEvent$1.run(TimedEvent.java:76) ~[?:?]
        at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftTask.run(CraftTask.java:82) ~[spigot-1.18-R0.1-SNAPSHOT.jar:3334-Spigot-a5dea1c-a008701]
        at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:415) ~[spigot-1.18-R0.1-SNAPSHOT.jar:3334-Spigot-a5dea1c-a008701]
        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1254) ~[spigot-1.18-R0.1-SNAPSHOT.jar:3334-Spigot-a5dea1c-a008701]
        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:428) ~[spigot-1.18-R0.1-SNAPSHOT.jar:3334-Spigot-a5dea1c-a008701]
        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1205) ~[spigot-1.18-R0.1-SNAPSHOT.jar:3334-Spigot-a5dea1c-a008701]
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1033) ~[spigot-1.18-R0.1-SNAPSHOT.jar:3334-Spigot-a5dea1c-a008701]
        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:303) ~[spigot-1.18-R0.1-SNAPSHOT.jar:3334-Spigot-a5dea1c-a008701]
        at java.lang.Thread.run(Thread.java:833) [?:?]`

**Comment by MagmaGuy** [comment]
Which EliteMobs version are you running?

**Comment by oraphaleao** [comment]
The last **7.3.10**

**Comment by oraphaleao** [comment]
Also, when starts the server, return this too:

`[EliteMobs] [EliteMobs] World em_adventurers_guild has been successfully loaded! It can be accessed through the '/ag' command, unless you changed that config option!
[10:36:15] [Server thread/ERROR]: Error occurred while enabling EliteMobs v7.3.9 (Is it up to date?)
java.lang.NoSuchFieldError: BARRIER
        at com.magmaguy.elitemobs.config.custombosses.premade.TestCustomBossesConfig.<init>(TestCustomBossesConfig.java:42) ~[?:?]
        at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?]
        at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
        at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
        at java.lang.reflect.ReflectAccess.newInstance(ReflectAccess.java:128) ~[?:?]
        at jdk.internal.reflect.ReflectionFactory.newInstance(ReflectionFactory.java:347) ~[?:?]
        at java.lang.Class.newInstance(Class.java:645) ~[?:?]
        at com.magmaguy.elitemobs.config.CustomConfig.lambda$new$0(CustomConfig.java:41) ~[?:?]
        at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?]
        at com.magmaguy.elitemobs.config.CustomConfig.<init>(CustomConfig.java:39) ~[?:?]
        at com.magmaguy.elitemobs.config.custombosses.CustomBossesConfig.<init>(CustomBossesConfig.java:16) ~[?:?]
        at com.magmaguy.elitemobs.EliteMobs.onEnable(EliteMobs.java:253) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[spigot-api-1.18-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342) ~[spigot-api-1.18-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) ~[spigot-api-1.18-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugin(CraftServer.java:525) ~[spigot-1.18-R0.1-SNAPSHOT.jar:3334-Spigot-a5dea1c-a008701]
        at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugins(CraftServer.java:439) ~[spigot-1.18-R0.1-SNAPSHOT.jar:3334-Spigot-a5dea1c-a008701]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:611) ~[spigot-1.18-R0.1-SNAPSHOT.jar:3334-Spigot-a5dea1c-a008701]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:412) ~[spigot-1.18-R0.1-SNAPSHOT.jar:3334-Spigot-a5dea1c-a008701]
        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:262) ~[spigot-1.18-R0.1-SNAPSHOT.jar:3334-Spigot-a5dea1c-a008701]
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:993) ~[spigot-1.18-R0.1-SNAPSHOT.jar:3334-Spigot-a5dea1c-a008701]
        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:303) ~[spigot-1.18-R0.1-SNAPSHOT.jar:3334-Spigot-a5dea1c-a008701]
        at java.lang.Thread.run(Thread.java:833) [?:?]`

**Comment by MagmaGuy** [comment]
Look at what you posted, it clearly says you're using EliteMobs 7.3.9. Update to 7.3.10.
