### ISSUE TITLE
Error while Starting the Server

### ISSUE THREAD

**Issue by mcdudu233** [MagmaGuy/EliteMobs#89]
Minecraft Version: 1.15 (yapfa)

[Server thread/ERROR]: Error occurred while enabling EliteMobs v7.3.10 (Is it up to date?)
java.lang.NoSuchFieldError: HOGLIN
	at com.magmaguy.elitemobs.config.QuestsConfig.setEntityTypes(QuestsConfig.java:83) ~[?:?]
	at com.magmaguy.elitemobs.config.QuestsConfig.initializeConfig(QuestsConfig.java:68) ~[?:?]
	at com.magmaguy.elitemobs.EliteMobs.initializeConfigs(EliteMobs.java:106) ~[?:?]
	at com.magmaguy.elitemobs.EliteMobs.onEnable(EliteMobs.java:154) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.15.2.jar:git-Paper-391]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.15.2.jar:git-Paper-391]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.15.2.jar:git-Paper-391]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:472) ~[patched_1.15.2.jar:git-Paper-391]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:386) ~[patched_1.15.2.jar:git-Paper-391]
	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:488) ~[patched_1.15.2.jar:git-Paper-391]
	at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:298) ~[patched_1.15.2.jar:git-Paper-391]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:909) ~[patched_1.15.2.jar:git-Paper-391]
	at java.lang.Thread.run(Thread.java:853) [?:1.8.0_312]
[21:03:10] [Server thread/INFO]: [EliteMobs] Disabling EliteMobs v7.3.10

**Comment by MagmaGuy** [comment]
Ah yeah, I seem to have forgotten to filter for older minecraft server versions when adding the quests. This has been resolved for the next snapshot build (7.3.11-SNAPSHOT-4)
