### ISSUE TITLE
Lots Errors in Console

### ISSUE THREAD

**Issue by oraphaleao** [MagmaGuy/EliteMobs#90]
Hello, everything working fine, but, this error is spawning lots in console:

`[18:02:12] [Server thread/ERROR]: Could not pass event EliteMobDeathEvent to EliteMobs v7.3.10
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-api-1.18-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-api-1.18-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[spigot-api-1.18-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[spigot-api-1.18-R0.1-SNAPSHOT.jar:?]
        at com.magmaguy.elitemobs.utils.EventCaller.<init>(EventCaller.java:8) ~[?:?]
        at com.magmaguy.elitemobs.api.EliteMobDeathEvent$EliteMobDeathEventFilter.onMobDeath(EliteMobDeathEvent.java:65) ~[?:?]
        at jdk.internal.reflect.GeneratedMethodAccessor332.invoke(Unknown Source) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-api-1.18-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-api-1.18-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[spigot-api-1.18-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[spigot-api-1.18-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R1.event.CraftEventFactory.callEntityDeathEvent(CraftEventFactory.java:809) ~[spigot-1.18-R0.1-SNAPSHOT.jar:3334-Spigot-a5dea1c-a008701]
        at net.minecraft.world.entity.EntityLiving.f(EntityLiving.java:1660) ~[spigot-1.18-R0.1-SNAPSHOT.jar:3334-Spigot-a5dea1c-a008701]
        at net.minecraft.world.entity.EntityLiving.a(EntityLiving.java:1600) ~[spigot-1.18-R0.1-SNAPSHOT.jar:3334-Spigot-a5dea1c-a008701]
        at net.minecraft.world.entity.EntityLiving.a(EntityLiving.java:1431) ~[spigot-1.18-R0.1-SNAPSHOT.jar:3334-Spigot-a5dea1c-a008701]
        at net.minecraft.world.entity.monster.EntityEnderman.a(EntityEnderman.java:386) ~[spigot-1.18-R0.1-SNAPSHOT.jar:3334-Spigot-a5dea1c-a008701]
        at net.minecraft.world.entity.player.EntityHuman.d(EntityHuman.java:1240) ~[spigot-1.18-R0.1-SNAPSHOT.jar:3334-Spigot-a5dea1c-a008701]
        at net.minecraft.server.level.EntityPlayer.d(EntityPlayer.java:1832) ~[spigot-1.18-R0.1-SNAPSHOT.jar:3334-Spigot-a5dea1c-a008701]
        at net.minecraft.server.network.PlayerConnection$4.a(PlayerConnection.java:2156) ~[spigot-1.18-R0.1-SNAPSHOT.jar:3334-Spigot-a5dea1c-a008701]
        at net.minecraft.network.protocol.game.PacketPlayInUseEntity$1.a(SourceFile:166) ~[spigot-1.18-R0.1-SNAPSHOT.jar:3334-Spigot-a5dea1c-a008701]
        at net.minecraft.network.protocol.game.PacketPlayInUseEntity.a(SourceFile:66) ~[spigot-1.18-R0.1-SNAPSHOT.jar:3334-Spigot-a5dea1c-a008701]
        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2091) ~[spigot-1.18-R0.1-SNAPSHOT.jar:3334-Spigot-a5dea1c-a008701]
        at net.minecraft.network.protocol.game.PacketPlayInUseEntity.a(SourceFile:53) ~[spigot-1.18-R0.1-SNAPSHOT.jar:3334-Spigot-a5dea1c-a008701]
        at net.minecraft.network.protocol.game.PacketPlayInUseEntity.a(SourceFile:13) ~[spigot-1.18-R0.1-SNAPSHOT.jar:3334-Spigot-a5dea1c-a008701]
        at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:30) ~[spigot-1.18-R0.1-SNAPSHOT.jar:3334-Spigot-a5dea1c-a008701]
        at net.minecraft.server.TickTask.run(SourceFile:18) ~[spigot-1.18-R0.1-SNAPSHOT.jar:3334-Spigot-a5dea1c-a008701]
        at net.minecraft.util.thread.IAsyncTaskHandler.c(SourceFile:151) ~[spigot-1.18-R0.1-SNAPSHOT.jar:3334-Spigot-a5dea1c-a008701]
        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.c(SourceFile:23) ~[spigot-1.18-R0.1-SNAPSHOT.jar:3334-Spigot-a5dea1c-a008701]
        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1157) ~[spigot-1.18-R0.1-SNAPSHOT.jar:3334-Spigot-a5dea1c-a008701]
        at net.minecraft.server.MinecraftServer.c(MinecraftServer.java:1) ~[spigot-1.18-R0.1-SNAPSHOT.jar:3334-Spigot-a5dea1c-a008701]
        at net.minecraft.util.thread.IAsyncTaskHandler.y(SourceFile:125) ~[spigot-1.18-R0.1-SNAPSHOT.jar:3334-Spigot-a5dea1c-a008701]
        at net.minecraft.server.MinecraftServer.bf(MinecraftServer.java:1136) ~[spigot-1.18-R0.1-SNAPSHOT.jar:3334-Spigot-a5dea1c-a008701]
        at net.minecraft.server.MinecraftServer.y(MinecraftServer.java:1129) ~[spigot-1.18-R0.1-SNAPSHOT.jar:3334-Spigot-a5dea1c-a008701]
        at net.minecraft.util.thread.IAsyncTaskHandler.bp(SourceFile:110) ~[spigot-1.18-R0.1-SNAPSHOT.jar:3334-Spigot-a5dea1c-a008701]
        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1112) ~[spigot-1.18-R0.1-SNAPSHOT.jar:3334-Spigot-a5dea1c-a008701]
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1037) ~[spigot-1.18-R0.1-SNAPSHOT.jar:3334-Spigot-a5dea1c-a008701]
        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:303) ~[spigot-1.18-R0.1-SNAPSHOT.jar:3334-Spigot-a5dea1c-a008701]
        at java.lang.Thread.run(Thread.java:833) [?:?]`

**Comment by MagmaGuy** [comment]
Try to get the full stacktrace, it's hard to tell exactly what is going on just from this.
