### ISSUE TITLE
Cannot invoke "org.bukkit.entity.LivingEntity.isValid()" because the return value of "com.magmaguy.elitemobs.mobconstructor.custombosses.CustomBossEntity.getLivingEntity()" is null

### ISSUE THREAD

**Issue by handy-git** [MagmaGuy/EliteMobs#96]
[21:03:47 WARN]: [EliteMobs] EliteMobs tried and failed to spawn necronomicon_zombie.yml . Possible reasons for this:
[21:03:47 WARN]: [EliteMobs] - The region was protected by a plugin (most likely)
[21:03:47 WARN]: [EliteMobs] - The spawn was interfered with by some incompatible third party plugin
[21:03:47 WARN]: [EliteMobs] Debug data: 
[21:03:47 WARN]: [EliteMobs] Chunk is loaded: true
[21:03:47 WARN]: [EliteMobs] Spawn type is normal spawn with chunk loaded: true
[21:03:47 WARN]: [EliteMobs] Attempted spawn location: Location{world=CraftWorld{name=world},x=-560.4361334004584,y=195.0,z=356.2419160305312,pitch=4.9283733,yaw=132.597}
[21:03:47 WARN]: [EliteMobs] Report the following to the developer at https://discord.gg/9f5QSka
[21:03:47 INFO]: EliteMobs version: 7.3.12 | Server version: git-Paper-181 (MC: 1.18.1)
[21:03:47 INFO]: java.base/java.lang.Thread.getStackTrace(Thread.java:1610)
[21:03:47 INFO]: EliteMobs-7.3.12.jar//com.magmaguy.elitemobs.utils.WarningMessage.<init>(WarningMessage.java:17)
[21:03:47 INFO]: EliteMobs-7.3.12.jar//com.magmaguy.elitemobs.mobconstructor.custombosses.CustomBossEntity.spawn(CustomBossEntity.java:247)
[21:03:47 INFO]: EliteMobs-7.3.12.jar//com.magmaguy.elitemobs.mobconstructor.custombosses.CustomBossEntity.spawn(CustomBossEntity.java:175)
[21:03:47 INFO]: EliteMobs-7.3.12.jar//com.magmaguy.elitemobs.mobconstructor.custombosses.CustomBossEntity.spawn(CustomBossEntity.java:158)
[21:03:47 INFO]: EliteMobs-7.3.12.jar//com.magmaguy.elitemobs.powers.majorpowers.zombie.ZombieNecronomicon$3.run(ZombieNecronomicon.java:210)
[21:03:47 INFO]: org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftTask.run(CraftTask.java:101)
[21:03:47 INFO]: org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483)
[21:03:47 INFO]: net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1547)
[21:03:47 INFO]: net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:480)
[21:03:47 INFO]: net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1470)
[21:03:47 INFO]: net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1264)
[21:03:47 INFO]: net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317)
[21:03:47 INFO]: java.base/java.lang.Thread.run(Thread.java:833)
[21:03:47 WARN]: [EliteMobs] Task #45120 for EliteMobs v7.3.12 generated an exception
java.lang.NullPointerException: Cannot invoke "org.bukkit.entity.LivingEntity.isValid()" because the return value of "com.magmaguy.elitemobs.mobconstructor.custombosses.CustomBossEntity.getLivingEntity()" is null
        at com.magmaguy.elitemobs.powers.majorpowers.zombie.ZombieNecronomicon$3.run(ZombieNecronomicon.java:212) ~[EliteMobs-7.3.12.jar:?]
        at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.18.1.jar:git-Paper-181]
        at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[paper-1.18.1.jar:git-Paper-181]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1547) ~[paper-1.18.1.jar:git-Paper-181]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:480) ~[paper-1.18.1.jar:git-Paper-181]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1470) ~[paper-1.18.1.jar:git-Paper-181]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1264) ~[paper-1.18.1.jar:git-Paper-181]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.1.jar:git-Paper-181]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by MagmaGuy** [comment]
This should be fixed.
